#!/usr/bin/env python3
"""Core review script for FlagGems PR review skill.

Takes PR diff data (from fetch_pr_diff.py or stdin) and runs structural checks,
outputting findings as JSON.

Usage:
    python review_operator.py <pr_number> [--repo owner/repo] [--json] [--strict]
    python review_operator.py --local [--base upstream/master] [--json]
    echo '...' | python review_operator.py --stdin [--json]
"""

from __future__ import annotations

import argparse
import ast
import json
import os
import re
import subprocess
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Optional


def verify_environment() -> None:
    """Verify required environment before proceeding."""
    # Check GH_TOKEN (only needed for non-stdin mode, but check early)
    if not os.getenv("GH_TOKEN"):
        print("WARNING: GH_TOKEN not set. PR mode will fail.", file=sys.stderr)
        print("Please run: gh auth login", file=sys.stderr)

    # Check if in git repo or FLAGGEMS_REPO is set
    repo_path = os.getenv("FLAGGEMS_REPO")
    if repo_path:
        repo_path = Path(repo_path).resolve()
        if not (repo_path / ".git").is_dir():
            print(f"ERROR: FLAGGEMS_REPO={repo_path} is not a git repository", file=sys.stderr)
            sys.exit(1)
        try:
            os.chdir(repo_path)
        except OSError as e:
            print(f"ERROR: Cannot cd to FLAGGEMS_REPO={repo_path}: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        # Check if current directory is in a git repo (only warn, not fatal for stdin mode)
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            print("WARNING: Not in a git repository and FLAGGEMS_REPO not set", file=sys.stderr)
            print("PR mode and local mode will fail.", file=sys.stderr)


@dataclass
class Finding:
    severity: str  # "error", "warning", "info"
    rule_id: str
    file: str
    line: int
    message: str
    suggestion: str = ""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def parse_added_lines(patch: str) -> list[tuple[int, str]]:
    """Extract (line_number, content) for added lines from a unified diff patch."""
    lines: list[tuple[int, str]] = []
    current_line = 0
    for raw in patch.splitlines():
        if raw.startswith("@@"):
            # Parse hunk header: @@ -a,b +c,d @@
            m = re.search(r"\+(\d+)", raw)
            if m:
                current_line = int(m.group(1))
            continue
        if raw.startswith("+") and not raw.startswith("+++"):
            lines.append((current_line, raw[1:]))
            current_line += 1
        elif raw.startswith("-") and not raw.startswith("---"):
            # Removed line, doesn't advance the new-file line counter
            continue
        else:
            current_line += 1
    return lines


def safe_ast_parse(content: str, filename: str = "<unknown>") -> ast.Module | None:
    """Try to parse Python source; return None on failure."""
    try:
        return ast.parse(content, filename=filename)
    except SyntaxError:
        return None


# ---------------------------------------------------------------------------
# Check functions
# ---------------------------------------------------------------------------

def check_kernel(file_info: dict, operator: str | None) -> list[Finding]:
    """Checks for kernel files: src/flag_gems/ops/<op>.py"""
    findings: list[Finding] = []
    path = file_info["path"]
    content = file_info.get("content", "")
    if not content:
        return findings

    # KERNEL_HEADER
    first_line = content.split("\n", 1)[0]
    if not first_line.startswith("# Generated by KernelGen"):
        findings.append(Finding(
            severity="error",
            rule_id="KERNEL_HEADER",
            file=path,
            line=1,
            message="First line does not start with '# Generated by KernelGen'",
            suggestion="Add '# Generated by KernelGen' as the first line if this is auto-generated.",
        ))

    # KERNEL_NO_PRINT (AST-based)
    tree = safe_ast_parse(content, path)
    if tree:
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                func = node.func
                if isinstance(func, ast.Name) and func.id == "print":
                    findings.append(Finding(
                        severity="error",
                        rule_id="KERNEL_NO_PRINT",
                        file=path,
                        line=node.lineno,
                        message="print() call found in kernel file",
                        suggestion="Remove print() or replace with logger.debug()",
                    ))

        # KERNEL_NO_DUP_FUNC
        names_seen: dict[str, int] = {}
        for node in ast.iter_child_nodes(tree):
            name = None
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                name = node.name
            if name:
                if name in names_seen:
                    findings.append(Finding(
                        severity="error",
                        rule_id="KERNEL_NO_DUP_FUNC",
                        file=path,
                        line=node.lineno,
                        message=f"Duplicate definition of '{name}' (first at line {names_seen[name]})",
                        suggestion="Remove the duplicate definition or rename one of them.",
                    ))
                else:
                    names_seen[name] = node.lineno

    # KERNEL_NO_FALLBACK
    if operator:
        esc = re.escape(operator)
        pattern = re.compile(rf"torch\.(?:Tensor\.)?{esc}_?\s*\(")
        for i, line in enumerate(content.splitlines(), 1):
            if line.lstrip().startswith("#"):
                continue
            if pattern.search(line):
                findings.append(Finding(
                    severity="error",
                    rule_id="KERNEL_NO_FALLBACK",
                    file=path,
                    line=i,
                    message=f"Calling torch.{operator}() in its own kernel causes infinite recursion",
                    suggestion="Use the underlying aten implementation or refactor the logic.",
                ))

    # KERNEL_NO_PRIVATE_API
    private_re = re.compile(r"torch\._\w+")
    for i, line in enumerate(content.splitlines(), 1):
        if private_re.search(line):
            findings.append(Finding(
                severity="warning",
                rule_id="KERNEL_NO_PRIVATE_API",
                file=path,
                line=i,
                message=f"Usage of private torch API: {private_re.search(line).group()}",
                suggestion="Use public torch APIs instead of private internals.",
            ))

    # KERNEL_NO_IS_CUDA
    is_cuda_re = re.compile(r'\.is_cuda|device\.type\s*==\s*["\']cuda["\']')
    for i, line in enumerate(content.splitlines(), 1):
        if is_cuda_re.search(line) and not line.strip().startswith("#"):
            findings.append(Finding(
                severity="error",
                rule_id="KERNEL_NO_IS_CUDA",
                file=path,
                line=i,
                message=f"CUDA-specific device check found: {is_cuda_re.search(line).group()}",
                suggestion="Use flag_gems.device instead of CUDA-specific checks for multi-backend compatibility.",
            ))

    # KERNEL_AUTOTUNE_CONFIG
    config_count = len(re.findall(r'triton\.Config\s*\(', content))
    if config_count >= 3:
        # Find the line of the first @triton.autotune
        for i, line in enumerate(content.splitlines(), 1):
            if '@triton.autotune' in line:
                findings.append(Finding(
                    severity="warning",
                    rule_id="KERNEL_AUTOTUNE_CONFIG",
                    file=path,
                    line=i,
                    message=f"Large inline autotune config ({config_count} configs hardcoded in kernel)",
                    suggestion="Move autotune configs to a config file instead of hardcoding inline.",
                ))
                break

    # KERNEL_LOGGER_FORMAT
    logger_re = re.compile(r'logger\.debug\s*\(\s*["\'](.+?)["\']')
    for i, line in enumerate(content.splitlines(), 1):
        m = logger_re.search(line)
        if m:
            msg = m.group(1)
            if not msg.startswith("GEMS ") or msg != msg.upper():
                findings.append(Finding(
                    severity="warning",
                    rule_id="KERNEL_LOGGER_FORMAT",
                    file=path,
                    line=i,
                    message=f"Logger message '{msg}' does not follow 'GEMS <OP_NAME_UPPER>' format",
                    suggestion='Use logger.debug("GEMS <OP_NAME_UPPER>") format.',
                ))

    # HYPERPARAMS
    hyperparam_re = re.compile(r'^\s*(BLOCK_\w+|NUM_WARPS|num_warps|num_stages|BLOCK_SIZE)\s*[=:]\s*\d+')
    lines_list = content.splitlines()
    for i, line in enumerate(lines_list):
        if hyperparam_re.search(line) and "#" not in line:
            prev_line = lines_list[i - 1] if i > 0 else ""
            if "#" not in prev_line:
                findings.append(Finding(
                    severity="warning",
                    rule_id="HYPERPARAMS",
                    file=path,
                    line=i + 1,
                    message=f"Hardcoded hyperparameter without comment: {line.strip()}",
                    suggestion="Add a comment explaining why this value was chosen.",
                ))

    return findings


def check_ops_init(file_info: dict, operator: str | None) -> list[Finding]:
    """Checks for src/flag_gems/ops/__init__.py."""
    findings: list[Finding] = []
    path = file_info["path"]
    content = file_info.get("content", "")
    if not content or not operator:
        return findings

    # REG_OPS_INIT: check import and __all__ entry
    import_pattern = re.compile(rf"from\s+flag_gems\.ops\.{re.escape(operator)}\s+import")
    has_import = bool(import_pattern.search(content))

    all_pattern = re.compile(r"__all__\s*=\s*\[([^\]]*)\]", re.DOTALL)
    all_match = all_pattern.search(content)
    has_all_entry = False
    if all_match:
        all_content = all_match.group(1)
        entries = re.findall(r'"([^"]+)"|\'([^\']+)\'', all_content)
        all_names = [e[0] or e[1] for e in entries]
        has_all_entry = operator in all_names

        # Check alphabetical order around the entry
        if has_all_entry:
            idx = all_names.index(operator)
            neighbors = all_names[max(0, idx - 1):idx + 2]
            if neighbors != sorted(neighbors):
                findings.append(Finding(
                    severity="warning",
                    rule_id="REG_OPS_INIT",
                    file=path,
                    line=1,
                    message=f"__all__ entries around '{operator}' are not in alphabetical order",
                    suggestion="Keep __all__ entries in alphabetical order.",
                ))

    if not has_import:
        findings.append(Finding(
            severity="error",
            rule_id="REG_OPS_INIT",
            file=path,
            line=1,
            message=f"Missing import for operator '{operator}' in ops/__init__.py",
            suggestion=f"Add 'from flag_gems.ops.{operator} import ...' to ops/__init__.py",
        ))

    if not has_all_entry:
        findings.append(Finding(
            severity="error",
            rule_id="REG_OPS_INIT",
            file=path,
            line=1,
            message=f"Operator '{operator}' not found in __all__ list",
            suggestion=f"Add '{operator}' to __all__ in alphabetical order.",
        ))

    return findings


def check_full_config(file_info: dict, operator: str | None, kernel_content: str = "") -> list[Finding]:
    """Checks for __init__.py containing _FULL_CONFIG."""
    findings: list[Finding] = []
    path = file_info["path"]
    content = file_info.get("content", "")
    if not content or not operator:
        return findings

    if "_FULL_CONFIG" not in content:
        return findings

    # REG_FULL_CONFIG: check entry exists
    # Look for the operator in _FULL_CONFIG dict-like structure
    entry_pattern = re.compile(rf'["\']({re.escape(operator)})["\']')
    if not entry_pattern.search(content):
        findings.append(Finding(
            severity="error",
            rule_id="REG_FULL_CONFIG",
            file=path,
            line=1,
            message=f"No _FULL_CONFIG entry found for operator '{operator}'",
            suggestion=f"Add an entry for '{operator}' to _FULL_CONFIG.",
        ))

    # Check for aten:: prefix (should not be present)
    aten_pattern = re.compile(r'["\']aten::' + re.escape(operator) + r'["\']')
    for i, line in enumerate(content.splitlines(), 1):
        if aten_pattern.search(line):
            findings.append(Finding(
                severity="error",
                rule_id="REG_FULL_CONFIG",
                file=path,
                line=i,
                message=f"_FULL_CONFIG entry uses 'aten::{operator}' prefix",
                suggestion="Remove the 'aten::' prefix from the config entry.",
            ))

    # Heuristic: check if target matches a @triton.jit function name
    if kernel_content:
        jit_funcs = set()
        jit_pattern = re.compile(r"@triton\.jit\s*\n\s*def\s+(\w+)")
        for m in jit_pattern.finditer(kernel_content):
            jit_funcs.add(m.group(1))

        # Look for targets in config that match jit function names
        target_pattern = re.compile(r'["\'](\w+)["\']')
        in_config = False
        for i, line in enumerate(content.splitlines(), 1):
            if "_FULL_CONFIG" in line:
                in_config = True
            if in_config:
                for m in target_pattern.finditer(line):
                    if m.group(1) in jit_funcs:
                        findings.append(Finding(
                            severity="warning",
                            rule_id="REG_FULL_CONFIG",
                            file=path,
                            line=i,
                            message=f"Config target '{m.group(1)}' matches a @triton.jit kernel name",
                            suggestion="The target should be the Python wrapper function, not the raw triton kernel.",
                        ))
                if line.strip().startswith("}") or line.strip().startswith("]"):
                    in_config = False

    return findings


def check_yaml(file_info: dict, operator: str | None) -> list[Finding]:
    """Checks for operators.yaml."""
    findings: list[Finding] = []
    path = file_info["path"]
    content = file_info.get("content", "")
    if not content or not operator:
        return findings

    try:
        import yaml
        data = yaml.safe_load(content)
    except Exception:
        # Fallback: basic regex parsing if pyyaml not available
        data = None

    if data is None:
        return findings

    if not isinstance(data, list):
        # Might be a dict with a top-level key
        if isinstance(data, dict):
            for v in data.values():
                if isinstance(v, list):
                    data = v
                    break
            else:
                return findings
        else:
            return findings

    required_fields = {"id", "description", "for", "labels", "kind", "stages"}
    ids_seen: dict[str, int] = {}
    found_entry = None

    for idx, entry in enumerate(data):
        if not isinstance(entry, dict):
            continue
        entry_id = entry.get("id", "")

        # REG_YAML_UNIQUE
        if entry_id in ids_seen:
            findings.append(Finding(
                severity="error",
                rule_id="REG_YAML_UNIQUE",
                file=path,
                line=idx + 1,
                message=f"Duplicate id '{entry_id}' in operators.yaml",
                suggestion="Each operator must have a unique id.",
            ))
        ids_seen[entry_id] = idx

        if entry_id == operator:
            found_entry = entry

    # REG_YAML_COMPLETE
    if found_entry is None:
        findings.append(Finding(
            severity="error",
            rule_id="REG_YAML_COMPLETE",
            file=path,
            line=1,
            message=f"No entry with id='{operator}' found in operators.yaml",
            suggestion=f"Add an entry for '{operator}' with all required fields.",
        ))
    else:
        missing = required_fields - set(found_entry.keys())
        if missing:
            findings.append(Finding(
                severity="error",
                rule_id="REG_YAML_COMPLETE",
                file=path,
                line=1,
                message=f"Entry '{operator}' missing required fields: {sorted(missing)}",
                suggestion=f"Add the missing fields: {sorted(missing)}",
            ))

    return findings


def check_test(file_info: dict, operator: str | None) -> list[Finding]:
    """Checks for test files: tests/test_<op>.py"""
    findings: list[Finding] = []
    path = file_info["path"]
    content = file_info.get("content", "")
    if not content:
        return findings

    op_id = operator.lstrip("_") if operator else None

    tree = safe_ast_parse(content, path)

    # TEST_NO_PRINT
    if tree:
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                func = node.func
                if isinstance(func, ast.Name) and func.id == "print":
                    findings.append(Finding(
                        severity="error",
                        rule_id="TEST_NO_PRINT",
                        file=path,
                        line=node.lineno,
                        message="print() call found in test file",
                        suggestion="Remove print() or replace with logging.",
                    ))

    # TEST_MARK
    if op_id and tree:
        mark_pattern = re.compile(r"@pytest\.mark\.(\w+)")
        for i, line in enumerate(content.splitlines(), 1):
            m = mark_pattern.search(line)
            if m:
                mark_name = m.group(1)
                # Skip common pytest marks
                if mark_name in ("parametrize", "skip", "skipif", "xfail", "usefixtures", "filterwarnings"):
                    continue
                if mark_name != op_id:
                    findings.append(Finding(
                        severity="error",
                        rule_id="TEST_MARK",
                        file=path,
                        line=i,
                        message=f"pytest.mark.{mark_name} does not match operator id '{op_id}'",
                        suggestion=f"Use @pytest.mark.{op_id} for consistency.",
                    ))

    # TEST_IMPORT
    bad_import_re = re.compile(r"^\s*import\s+accuracy_utils")
    bad_from_re = re.compile(r"^\s*from\s+flag_gems")
    good_import_re = re.compile(r"^\s*from\s+\.\s+import\s+accuracy_utils")
    for i, line in enumerate(content.splitlines(), 1):
        if good_import_re.match(line):
            pass
        if bad_import_re.match(line):
            findings.append(Finding(
                severity="error",
                rule_id="TEST_IMPORT",
                file=path,
                line=i,
                message="Direct 'import accuracy_utils' should use relative import",
                suggestion="Use 'from . import accuracy_utils' instead.",
            ))
        if bad_from_re.match(line) and "accuracy_utils" in line:
            findings.append(Finding(
                severity="error",
                rule_id="TEST_IMPORT",
                file=path,
                line=i,
                message="Absolute import from flag_gems in test; use relative import",
                suggestion="Use 'from . import accuracy_utils' instead.",
            ))

    # TEST_ASSERT
    assert_re = re.compile(r"gems_assert_(close|equal)")
    if not assert_re.search(content):
        findings.append(Finding(
            severity="error",
            rule_id="TEST_ASSERT",
            file=path,
            line=1,
            message="No gems_assert_close or gems_assert_equal call found in test",
            suggestion="Use gems_assert_close or gems_assert_equal for result validation.",
        ))

    # TEST_NO_RTOL
    rtol_re = re.compile(r"gems_assert_close\s*\([^)]*rtol")
    for i, line in enumerate(content.splitlines(), 1):
        if rtol_re.search(line):
            findings.append(Finding(
                severity="error",
                rule_id="TEST_NO_RTOL",
                file=path,
                line=i,
                message="Explicit rtol in gems_assert_close; use default tolerance",
                suggestion="Remove rtol parameter and rely on the default tolerance.",
            ))

    # TEST_TO_REFERENCE
    if "gems_assert" in content and "to_reference" not in content:
        findings.append(Finding(
            severity="error",
            rule_id="TEST_TO_REFERENCE",
            file=path,
            line=1,
            message="Test uses gems_assert but no to_reference() call found",
            suggestion="Use utils.to_reference() for all tensors in reference computation.",
        ))

    # DTYPE_HARDCODE
    dtype_list_re = re.compile(r"\[.*torch\.\w+.*,.*torch\.\w+.*\]")
    for i, line in enumerate(content.splitlines(), 1):
        if dtype_list_re.search(line) and "dtype" in line.lower():
            if "#" not in line:
                findings.append(Finding(
                    severity="warning",
                    rule_id="DTYPE_HARDCODE",
                    file=path,
                    line=i,
                    message="Hardcoded dtype list without explanatory comment",
                    suggestion="Use utils.FLOAT_DTYPES or add a comment explaining the specific dtypes.",
                ))

    return findings


def check_benchmark(file_info: dict, operator: str | None) -> list[Finding]:
    """Checks for benchmark files: benchmark/test_<op>.py"""
    findings: list[Finding] = []
    path = file_info["path"]
    content = file_info.get("content", "")
    if not content:
        return findings

    op_id = operator.lstrip("_") if operator else None

    # BENCH_MARK
    if op_id:
        mark_pattern = re.compile(r"@pytest\.mark\.(\w+)")
        for i, line in enumerate(content.splitlines(), 1):
            m = mark_pattern.search(line)
            if m:
                mark_name = m.group(1)
                if mark_name in ("parametrize", "skip", "skipif", "xfail", "usefixtures", "filterwarnings"):
                    continue
                if mark_name != op_id:
                    findings.append(Finding(
                        severity="error",
                        rule_id="BENCH_MARK",
                        file=path,
                        line=i,
                        message=f"pytest.mark.{mark_name} does not match operator id '{op_id}'",
                        suggestion=f"Use @pytest.mark.{op_id} for consistency.",
                    ))

    # BENCH_OP_NAME
    if op_id:
        op_name_re = re.compile(r'op_name\s*=\s*["\']([^"\']+)["\']')
        for i, line in enumerate(content.splitlines(), 1):
            m = op_name_re.search(line)
            if m and m.group(1) != op_id:
                findings.append(Finding(
                    severity="error",
                    rule_id="BENCH_OP_NAME",
                    file=path,
                    line=i,
                    message=f"op_name='{m.group(1)}' does not match operator id '{op_id}'",
                    suggestion=f"Set op_name=\"{op_id}\".",
                ))

    # BENCH_CLASS
    standard_classes = {
        "UnaryPointwiseBenchmark", "BinaryPointwiseBenchmark",
        "UnaryReductionBenchmark", "BlasBenchmark", "GenericBenchmark",
    }
    class_re = re.compile(r"class\s+\w+\s*\((\w+)\)")
    for i, line in enumerate(content.splitlines(), 1):
        m = class_re.search(line)
        if m:
            base = m.group(1)
            if base.endswith("Benchmark") and base not in standard_classes:
                findings.append(Finding(
                    severity="warning",
                    rule_id="BENCH_CLASS",
                    file=path,
                    line=i,
                    message=f"Non-standard benchmark class '{base}'",
                    suggestion=f"Consider using one of: {', '.join(sorted(standard_classes))}",
                ))

    # BENCH_DTYPE
    dtype_list_re = re.compile(r"\[.*torch\.\w+.*,.*torch\.\w+.*\]")
    for i, line in enumerate(content.splitlines(), 1):
        if dtype_list_re.search(line):
            # Check if there's a comment explaining why
            if "#" not in line:
                findings.append(Finding(
                    severity="warning",
                    rule_id="BENCH_DTYPE",
                    file=path,
                    line=i,
                    message="Hardcoded dtype list without explanatory comment",
                    suggestion="Add a comment explaining why these specific dtypes are tested.",
                ))

    # BENCH_FAIRNESS
    if "backward" in path.lower() or "backward" in content.lower():
        if re.search(r'\.backward\s*\(', content) and re.search(r'\.requires_grad', content):
            for i, line in enumerate(content.splitlines(), 1):
                if '.backward(' in line:
                    findings.append(Finding(
                        severity="error",
                        rule_id="BENCH_FAIRNESS",
                        file=path,
                        line=i,
                        message="Benchmark may run forward+backward in torch wrapper but only backward in gems",
                        suggestion="Use torch.ops.aten.<op>_backward() directly for fair comparison.",
                    ))
                    break

    return findings


def check_cross_file(files: list[dict], commits: list[str], operator: str | None) -> list[Finding]:
    """Cross-file checks."""
    findings: list[Finding] = []

    # GIT_COAUTHOR — only check the latest commit (older commits don't affect CLA CI)
    if commits:
        latest_commit = commits[-1]
        if re.search(r"Co-Authored-By", latest_commit, re.IGNORECASE):
            findings.append(Finding(
                severity="error",
                rule_id="GIT_COAUTHOR",
                file="<commit>",
                line=0,
                message="Latest commit contains Co-Authored-By trailer",
                suggestion="Remove Co-Authored-By from the latest commit to pass CLA CI.",
            ))

    # SINGLE_OP
    op_pattern = re.compile(r"src/flag_gems/ops/([^/]+)\.py$")
    ops_found: set[str] = set()
    for f in files:
        m = op_pattern.search(f["path"])
        if m and m.group(1) != "__init__":
            ops_found.add(m.group(1))
    if len(ops_found) > 1:
        findings.append(Finding(
            severity="warning",
            rule_id="SINGLE_OP",
            file="<multiple>",
            line=0,
            message=f"PR modifies multiple operators: {sorted(ops_found)}",
            suggestion="Consider splitting into separate PRs for easier review.",
        ))

    # CODE_QUALITY (on added lines)
    for f in files:
        patch = f.get("patch", "")
        if not patch:
            continue
        added_lines = parse_added_lines(patch)
        for lineno, line_content in added_lines:
            if len(line_content) > 120:
                findings.append(Finding(
                    severity="warning",
                    rule_id="CODE_QUALITY",
                    file=f["path"],
                    line=lineno,
                    message=f"Line exceeds 120 characters ({len(line_content)} chars)",
                    suggestion="Consider breaking the line for readability.",
                ))
            if line_content != line_content.rstrip():
                findings.append(Finding(
                    severity="warning",
                    rule_id="CODE_QUALITY",
                    file=f["path"],
                    line=lineno,
                    message="Trailing whitespace on added line",
                    suggestion="Remove trailing whitespace.",
                ))

    return findings


def check_yaml_consistency(
    files: list[dict], operator: str | None
) -> list[Finding]:
    """REG_CONSISTENCY: check yaml `for` list entries match _FULL_CONFIG entries."""
    findings: list[Finding] = []
    if not operator:
        return findings

    yaml_content = ""
    config_content = ""
    yaml_path = ""

    for f in files:
        if "operators.yaml" in f["path"]:
            yaml_content = f.get("content", "")
            yaml_path = f["path"]
        if "__init__.py" in f["path"] and "_FULL_CONFIG" in f.get("content", ""):
            config_content = f.get("content", "")
            f["path"]

    if not yaml_content or not config_content:
        return findings

    # Extract `for` list from yaml entry (basic regex since yaml may not be available)
    try:
        import yaml
        data = yaml.safe_load(yaml_content)
        if isinstance(data, dict):
            for v in data.values():
                if isinstance(v, list):
                    data = v
                    break
        if isinstance(data, list):
            for entry in data:
                if isinstance(entry, dict) and entry.get("id") == operator:
                    yaml_for = set(entry.get("for", []))
                    break
            else:
                yaml_for = set()
        else:
            yaml_for = set()
    except Exception:
        yaml_for = set()

    # Extract config keys related to operator (heuristic)
    config_keys: set[str] = set()
    op_section_re = re.compile(rf'["\']({re.escape(operator)}[^"\']*)["\']')
    for m in op_section_re.finditer(config_content):
        config_keys.add(m.group(1))

    # If we have both, check consistency
    if yaml_for and config_keys:
        missing_in_config = yaml_for - config_keys
        if missing_in_config:
            findings.append(Finding(
                severity="error",
                rule_id="REG_CONSISTENCY",
                file=yaml_path,
                line=1,
                message=f"YAML 'for' entries not in _FULL_CONFIG: {sorted(missing_in_config)}",
                suggestion="Ensure all YAML 'for' entries have matching _FULL_CONFIG entries.",
            ))

    return findings


# ---------------------------------------------------------------------------
# File categorization
# ---------------------------------------------------------------------------

def categorize_file(path: str) -> str:
    """Categorize a file path into a check category."""
    if re.match(r"src/flag_gems/ops/[^/]+\.py$", path):
        basename = Path(path).stem
        if basename == "__init__":
            return "ops_init"
        return "kernel"
    if re.match(r"src/flag_gems/__init__\.py$", path):
        return "full_config"
    if "operators.yaml" in path:
        return "yaml"
    if re.match(r"tests/test_[^/]+\.py$", path):
        return "test"
    if re.match(r"benchmark/test_[^/]+\.py$", path):
        return "benchmark"
    return "other"


# ---------------------------------------------------------------------------
# Main orchestration
# ---------------------------------------------------------------------------

def run_review(data: dict, strict: bool = False) -> list[Finding]:
    """Run all checks on the input data and return findings."""
    operator = data.get("operator")
    files = data.get("files", [])
    commits = data.get("commits", [])

    all_findings: list[Finding] = []

    # Get kernel content for cross-referencing
    kernel_content = ""
    for f in files:
        if categorize_file(f["path"]) == "kernel":
            kernel_content = f.get("content", "")
            break

    # Per-file checks
    for f in files:
        if f.get("status") == "removed":
            continue

        category = categorize_file(f["path"])
        if category == "kernel":
            all_findings.extend(check_kernel(f, operator))
        elif category == "ops_init":
            all_findings.extend(check_ops_init(f, operator))
        elif category == "full_config":
            all_findings.extend(check_full_config(f, operator, kernel_content))
        elif category == "yaml":
            all_findings.extend(check_yaml(f, operator))
        elif category == "test":
            all_findings.extend(check_test(f, operator))
        elif category == "benchmark":
            all_findings.extend(check_benchmark(f, operator))

    # TEST_EXISTS / BENCH_EXISTS
    if operator:
        op_id = operator.lstrip("_")
        file_paths = {f["path"] for f in files}
        has_kernel = any(categorize_file(p) == "kernel" for p in file_paths)
        has_test = any(f"tests/test_{op_id}.py" in p for p in file_paths)
        has_bench = any(f"benchmark/test_{op_id}.py" in p for p in file_paths)

        if has_kernel and not has_test:
            all_findings.append(Finding(
                severity="error",
                rule_id="TEST_EXISTS",
                file=f"tests/test_{op_id}.py",
                line=0,
                message=f"No test file found for operator '{operator}'",
                suggestion=f"Add tests/test_{op_id}.py with accuracy tests.",
            ))
        if has_kernel and not has_bench:
            all_findings.append(Finding(
                severity="error",
                rule_id="BENCH_EXISTS",
                file=f"benchmark/test_{op_id}.py",
                line=0,
                message=f"No benchmark file found for operator '{operator}'",
                suggestion=f"Add benchmark/test_{op_id}.py with performance benchmarks.",
            ))

    # Cross-file checks
    all_findings.extend(check_cross_file(files, commits, operator))
    all_findings.extend(check_yaml_consistency(files, operator))

    # In strict mode, promote warnings to errors
    if strict:
        for f in all_findings:
            if f.severity == "warning":
                f.severity = "error"

    return all_findings


def format_terminal(findings: list[Finding]) -> str:
    """Format findings as a colored terminal table."""
    if not findings:
        return "\033[32m No issues found.\033[0m\n"

    severity_colors = {
        "error": "\033[31m",    # red
        "warning": "\033[33m",  # yellow
        "info": "\033[36m",     # cyan
    }
    reset = "\033[0m"

    lines: list[str] = []
    lines.append(f"\n{'Severity':<10} {'Rule':<22} {'File':<45} {'Line':<6} Message")
    lines.append("-" * 120)

    for f in findings:
        color = severity_colors.get(f.severity, "")
        sev = f"{color}{f.severity.upper():<10}{reset}"
        file_short = f.file if len(f.file) <= 44 else "..." + f.file[-41:]
        lines.append(f"{sev} {f.rule_id:<22} {file_short:<45} {f.line:<6} {f.message}")
        if f.suggestion:
            lines.append(f"{'':>10} {'':>22} {'':>45} {'':>6} -> {f.suggestion}")

    error_count = sum(1 for f in findings if f.severity == "error")
    warn_count = sum(1 for f in findings if f.severity == "warning")
    info_count = sum(1 for f in findings if f.severity == "info")
    lines.append("")
    lines.append(
        f"Summary: {error_count} error(s), {warn_count} warning(s), {info_count} info"
    )

    return "\n".join(lines) + "\n"


def main() -> None:
    # Verify environment first (warnings only, not fatal for stdin mode)
    verify_environment()

    parser = argparse.ArgumentParser(
        description="FlagGems PR review: structural checks on operator PRs.",
    )
    parser.add_argument(
        "pr_number",
        nargs="?",
        type=int,
        help="Pull request number (fetches data via fetch_pr_diff.py)",
    )
    parser.add_argument(
        "--repo",
        type=str,
        default=None,
        help="Repository in owner/repo format",
    )
    parser.add_argument(
        "--local",
        action="store_true",
        help="Use local mode (passed to fetch_pr_diff.py)",
    )
    parser.add_argument(
        "--base",
        type=str,
        default="upstream/master",
        help="Base ref for local mode (default: upstream/master)",
    )
    parser.add_argument(
        "--stdin",
        action="store_true",
        help="Read JSON input from stdin instead of calling fetch_pr_diff.py",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output findings as JSON (default for stdout when piped)",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Treat warnings as errors",
    )

    args = parser.parse_args()

    # Get input data
    if args.stdin:
        data = json.load(sys.stdin)
    else:
        # Build command to invoke fetch_pr_diff.py
        script_dir = Path(__file__).resolve().parent
        fetch_script = script_dir / "fetch_pr_diff.py"

        cmd = [sys.executable, str(fetch_script)]
        if args.local:
            cmd.append("--local")
            cmd.extend(["--base", args.base])
        elif args.pr_number is not None:
            cmd.append(str(args.pr_number))
            if args.repo:
                cmd.extend(["--repo", args.repo])
        else:
            parser.error("Provide a PR number, use --local, or use --stdin")

        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"Error fetching PR data: {result.stderr.strip()}", file=sys.stderr)
            sys.exit(1)
        try:
            data = json.loads(result.stdout)
        except json.JSONDecodeError as e:
            print(f"Error: fetch_pr_diff.py returned invalid JSON: {e}", file=sys.stderr)
            print(f"stdout: {result.stdout[:500]}", file=sys.stderr)
            sys.exit(1)

    # Run review
    findings = run_review(data, strict=args.strict)

    # Output
    use_json = args.json or not sys.stdout.isatty()
    if use_json:
        output = {
            "operator": data.get("operator"),
            "findings": [asdict(f) for f in findings]
        }
        json.dump(output, sys.stdout, indent=2, ensure_ascii=False)
        print()
    else:
        sys.stdout.write(format_terminal(findings))

    # Exit code: always 0 for normal operation (findings are in the JSON output)
    # Only non-zero exit codes come from actual script errors (e.g., fetch failure above)


if __name__ == "__main__":
    main()
