#!/usr/bin/env python3
"""FlagGems 算子 PR 提交前自动化检查脚本。

用法:
    python check_operator.py <operator_name> [--repo-dir /path/to/FlagGems]

检查项:
    1. kernel 文件存在且内容合规
    2. __init__.py 注册（ops 和顶层）
    3. operators.yaml 条目（含重复检测、下划线命名）
    4. 独立测试文件（含 dtype 硬编码检测、mark 命名）
    5. 独立 benchmark 文件（含 dtype 硬编码检测、mark 命名）
    6. 代码质量（重复函数、print、unused import 等）
    7. _FULL_CONFIG 映射目标验证
    8. 命名规范（下划线前缀算子的 mark/id 规则）
    9. KernelGen 首行注释
   10. gems_assert_close 禁止 rtol 参数
   11. Co-Authored-By 检查
   12. inplace mark 守卫
   13. 测试函数命名规范
   14. 显式 .cpu()/.to(torch.float64) 检测
   15. yaml/config 注册一致性
   16. anti-hack Layer 1 AST 扫描
   17. 单算子 PR 验证
   18. @use_tl_extra 桩函数检查
   19. benchmark case 数量统计
"""

import argparse
import ast
import importlib.util
import os
import re
import subprocess
import sys

import yaml


class Colors:
    OK = "\033[92m"
    WARN = "\033[93m"
    FAIL = "\033[91m"
    BOLD = "\033[1m"
    END = "\033[0m"


def ok(msg):
    print(f"  {Colors.OK}✓{Colors.END} {msg}")


def warn(msg):
    print(f"  {Colors.WARN}⚠{Colors.END} {msg}")


def fail(msg):
    print(f"  {Colors.FAIL}✗{Colors.END} {msg}")


def section(msg):
    print(f"\n{Colors.BOLD}[{msg}]{Colors.END}")


class OperatorChecker:
    def __init__(self, op_name, repo_dir):
        self.op_name = op_name
        self.repo_dir = repo_dir
        self.errors = []
        self.warnings = []

        # 下划线前缀的算子，mark 和 yaml id 需要去掉前导下划线
        self.op_id = op_name.lstrip("_")
        self.has_leading_underscore = op_name.startswith("_")

        self.kernel_path = os.path.join(repo_dir, "src/flag_gems/ops", f"{op_name}.py")
        self.ops_init_path = os.path.join(repo_dir, "src/flag_gems/ops/__init__.py")
        self.top_init_path = os.path.join(repo_dir, "src/flag_gems/__init__.py")
        self.yaml_path = os.path.join(repo_dir, "conf/operators.yaml")
        # 测试/benchmark 文件名使用 op_id（去掉前导下划线）
        self.test_path = os.path.join(repo_dir, "tests", f"test_{self.op_id}.py")
        self.bench_path = os.path.join(repo_dir, "benchmark", f"test_{self.op_id}.py")
        # 旧版错误路径（用于检测）
        if self.has_leading_underscore:
            self.wrong_test_path = os.path.join(repo_dir, "tests", f"test_{op_name}.py")
            self.wrong_bench_path = os.path.join(repo_dir, "benchmark", f"test_{op_name}.py")
        else:
            self.wrong_test_path = None
            self.wrong_bench_path = None

    def run_all(self):
        if self.has_leading_underscore:
            section("命名规则提示")
            ok(f"检测到下划线前缀算子: {self.op_name}")
            ok(f"  文件名/函数名/import/_FULL_CONFIG: 保留 {self.op_name}")
            ok(f"  pytest mark / yaml id: 使用 {self.op_id}（去掉前导下划线）")

        self.check_kernel()
        self.check_ops_init()
        self.check_top_init()
        self.check_operators_yaml()
        self.check_test_file()
        self.check_benchmark_file()
        self.check_code_quality()
        self.check_upstream_conflict()
        self.check_git_commit_message()
        self.check_inplace_mark()
        self.check_yaml_config_consistency()
        self.check_fallback_recursion()
        self.check_anti_hack()
        self.check_anti_hack_layer2()
        self.check_single_op_per_pr()
        self.check_use_tl_extra_stubs()
        self.check_hardcoded_sizes()
        self.check_benchmark_case_count()
        self.check_alias_wrappers()
        self.check_nan_handling()
        self.check_worktree_diff()
        self.check_dtype_assert_in_wrapper()
        self.print_summary()
        return len(self.errors) == 0

    def check_kernel(self):
        section("Kernel 文件检查")
        if not os.path.isfile(self.kernel_path):
            self.errors.append(f"kernel 文件不存在: {self.kernel_path}")
            fail(f"文件不存在: {self.kernel_path}")
            return

        ok(f"文件存在: {self.kernel_path}")

        with open(self.kernel_path) as f:
            content = f.read()

        # KernelGen 首行注释检查
        first_line = content.split("\n")[0] if content else ""
        if first_line.startswith("# Generated by KernelGen"):
            ok("首行包含 KernelGen 注释")
        else:
            self.errors.append("kernel 文件首行必须是 '# Generated by KernelGen: ...'")
            fail("首行缺少 KernelGen 注释")

        if "import logging" not in content or "logger" not in content:
            self.warnings.append("kernel 文件未使用 logging 模块")
            warn("未使用 logging 模块（建议用 logger = logging.getLogger(__name__)）")
        else:
            ok("使用了 logging 模块")

        if "print(" in content:
            self.errors.append("kernel 文件中使用了 print()")
            fail("包含 print() 调用 — 应使用 logger.debug()")
        else:
            ok("无 print() 调用")

        self._check_duplicate_functions(content, self.kernel_path)

        try:
            tree = ast.parse(content)
        except SyntaxError as e:
            self.errors.append(f"kernel 文件语法错误: {e}")
            fail(f"Python 语法错误: {e}")
            return

        # 检查未使用的 import torch
        has_torch_import = False
        torch_used_in_annotation_or_call = False
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    if alias.name == "torch":
                        has_torch_import = True
            if isinstance(node, ast.Attribute):
                if isinstance(node.value, ast.Name) and node.value.id == "torch":
                    torch_used_in_annotation_or_call = True
            if isinstance(node, ast.Name) and node.id == "torch":
                torch_used_in_annotation_or_call = True

        if has_torch_import and not torch_used_in_annotation_or_call:
            self.warnings.append("kernel 文件 import torch 但未实际使用（flake8 F401）")
            warn("import torch 但未使用 — flake8 会报 F401，提交前需删除")
        elif has_torch_import:
            ok("import torch 已使用")
        else:
            ok("无多余的 torch import")

        # 收集导出函数和 jit 函数信息
        exported = [
            n.name for n in ast.walk(tree)
            if isinstance(n, ast.FunctionDef)
            and not any(
                (isinstance(d, ast.Attribute) and d.attr == "jit")
                or (isinstance(d, ast.Name) and d.id == "jit")
                for d in n.decorator_list
            )
        ]
        jit_funcs = [
            n.name for n in ast.walk(tree)
            if isinstance(n, ast.FunctionDef) and any(
                (isinstance(d, ast.Attribute) and d.attr == "jit")
                or (isinstance(d, ast.Name) and d.id == "jit")
                for d in n.decorator_list
            )
        ]

        if exported:
            ok(f"导出函数: {', '.join(exported)}")
        else:
            self.warnings.append("未找到非 jit 导出函数")
            warn("未找到公开的非 @triton.jit 函数")

        if jit_funcs:
            ok(f"Triton kernel: {', '.join(jit_funcs)}")

        # 保存供 _FULL_CONFIG 验证使用
        self._kernel_exported = exported
        self._kernel_jit_funcs = jit_funcs

        # _out 变体检测：如果导出了 xxx_out 函数，test/benchmark 中必须覆盖
        out_funcs = [f for f in exported if f.endswith("_out")]
        if out_funcs:
            for out_func in out_funcs:
                self._check_out_variant_coverage(out_func)

    def check_ops_init(self):
        section("ops/__init__.py 注册检查")
        if not os.path.isfile(self.ops_init_path):
            self.errors.append("ops/__init__.py 不存在")
            fail("文件不存在")
            return

        with open(self.ops_init_path) as f:
            content = f.read()

        import_pattern = rf"from flag_gems\.ops\.{re.escape(self.op_name)} import"
        if re.search(import_pattern, content):
            ok(f"找到 import: from flag_gems.ops.{self.op_name} import ...")

            try:
                tree_init = ast.parse(content)
                imported_names = []
                for node in ast.walk(tree_init):
                    if isinstance(node, ast.ImportFrom) and node.module == f"flag_gems.ops.{self.op_name}":
                        for alias in node.names:
                            imported_names.append(alias.asname or alias.name)
                if imported_names:
                    ok(f"  导入名称: {', '.join(imported_names)}")
                    # 检查是否导出了 triton kernel 函数（不应该）
                    if hasattr(self, "_kernel_jit_funcs"):
                        leaked = set(imported_names) & set(self._kernel_jit_funcs)
                        if leaked:
                            self.errors.append(f"ops/__init__.py 不应导出 triton kernel 函数: {', '.join(leaked)}")
                            fail(f"  不应导出 triton kernel: {', '.join(leaked)}")
            except SyntaxError:
                pass
        else:
            self.errors.append(f"ops/__init__.py 中缺少 from flag_gems.ops.{self.op_name} import ...")
            fail(f"缺少 import 行: from flag_gems.ops.{self.op_name} import ...")

        all_match = re.search(r"__all__\s*=\s*\[([^\]]+)\]", content, re.DOTALL)
        if all_match:
            all_content = all_match.group(1)
            if f'"{self.op_name}"' in all_content or f"'{self.op_name}'" in all_content:
                ok(f'__all__ 中包含 "{self.op_name}"')
            else:
                self.errors.append(f'__all__ 中缺少 "{self.op_name}"')
                fail(f'__all__ 中缺少 "{self.op_name}"')
        else:
            self.warnings.append("未找到 __all__ 定义")
            warn("未找到 __all__ 列表")

        self._check_alphabetical_order_init(content)

    def check_top_init(self):
        section("顶层 __init__.py (_FULL_CONFIG) 检查")
        if not os.path.isfile(self.top_init_path):
            self.errors.append("顶层 __init__.py 不存在")
            fail("文件不存在")
            return

        with open(self.top_init_path) as f:
            content = f.read()

        config_match = re.search(r"_FULL_CONFIG\s*=\s*\((.+?)\)\s*\n\n", content, re.DOTALL)
        if not config_match:
            config_match = re.search(r"_FULL_CONFIG\s*=\s*\((.+?)\)\s*$", content, re.DOTALL)

        if not config_match:
            self.warnings.append("未找到 _FULL_CONFIG 定义")
            warn("未找到 _FULL_CONFIG")
            return

        config_text = config_match.group(1)

        # 查找包含 op_name 的注册条目
        found = False
        pattern = rf'\(\s*["\'](?:[^"\']*\.)?_?{re.escape(self.op_name)}(?:\.[^"\']*)?["\']\s*,\s*(\w+)'
        matches = re.findall(pattern, config_text)
        if matches:
            found = True
            for target_func in matches:
                ok(f'_FULL_CONFIG 中找到 "{self.op_name}" → {target_func}')
                # 验证映射目标不是 triton kernel
                if hasattr(self, "_kernel_jit_funcs") and target_func in self._kernel_jit_funcs:
                    self.errors.append(
                        f"_FULL_CONFIG 中 {self.op_name} 映射到了 triton kernel '{target_func}'"
                        f"，应映射到 wrapper 函数 '{self.op_name}'"
                    )
                    fail(f"  映射目标 '{target_func}' 是 triton kernel! 应映射到 wrapper 函数")

        if not found:
            # 尝试更宽松的匹配
            if f'"{self.op_name}"' in config_text or f"'{self.op_name}'" in config_text:
                found = True
                ok(f'_FULL_CONFIG 中找到 "{self.op_name}" 注册')

        if not found:
            self.errors.append(f"_FULL_CONFIG 中缺少 {self.op_name} 注册")
            fail(f"_FULL_CONFIG 中未找到 {self.op_name} 的注册条目")

        # aten name 格式验证: special.* 算子必须用 "special.xxx" 而非 "special_xxx"
        if config_match:
            config_text_full = config_match.group(1)
            bad_special = re.findall(
                r'\(\s*"(special_\w+)"\s*,', config_text_full
            )
            # 只报告与当前算子相关的
            for bad_name in bad_special:
                base = bad_name.replace("special_", "")
                if base == self.op_id or base == self.op_name or self.op_name.startswith("special"):
                    correct_name = bad_name.replace("special_", "special.", 1)
                    self.errors.append(
                        f'_FULL_CONFIG 中 aten name "{bad_name}" 格式错误，'
                        f'special.* 类算子应使用 "{correct_name}"'
                    )
                    fail(f'aten name 格式错误: "{bad_name}" → 应为 "{correct_name}"')

    def check_operators_yaml(self):
        section("conf/operators.yaml 检查")
        if not os.path.isfile(self.yaml_path):
            self.errors.append("operators.yaml 不存在")
            fail("文件不存在")
            return

        with open(self.yaml_path) as f:
            try:
                data = yaml.safe_load(f)
            except yaml.YAMLError as e:
                self.errors.append(f"operators.yaml 解析失败: {e}")
                fail(f"YAML 解析失败: {e}")
                return

        ops = data.get("ops", [])

        # 检查重复条目
        id_counts = {}
        for op in ops:
            op_id = op.get("id", "")
            id_counts[op_id] = id_counts.get(op_id, 0) + 1

        # 查找匹配的条目（使用 op_id，即去掉前导下划线的版本）
        found = None
        for op in ops:
            if op.get("id") == self.op_id:
                found = op
                break

        if not found:
            self.errors.append(f"operators.yaml 中缺少 id: {self.op_id}")
            fail(f"缺少条目 id: {self.op_id}")
            if self.has_leading_underscore:
                # 检查是否错误地用了带下划线的 id
                for op in ops:
                    if op.get("id") == self.op_name:
                        self.errors.append(
                            f"operators.yaml 中 id 使用了 '{self.op_name}'（带下划线），"
                            f"应改为 '{self.op_id}'（去掉前导下划线）"
                        )
                        fail(f"  发现错误的 id: '{self.op_name}' → 应为 '{self.op_id}'")
                        break
            return

        ok(f"找到条目 id: {self.op_id}")

        # 检查重复
        if id_counts.get(self.op_id, 0) > 1:
            self.errors.append(
                f"operators.yaml 中 id '{self.op_id}' 出现了 {id_counts[self.op_id]} 次（应只有 1 次）"
            )
            fail(f"  id '{self.op_id}' 重复了 {id_counts[self.op_id]} 次!")
        else:
            ok("  无重复条目")

        required_fields = ["id", "description", "for", "labels", "kind", "stages"]
        for field in required_fields:
            if field in found:
                ok(f"  字段 {field}: ✓")
            else:
                self.errors.append(f"operators.yaml 条目缺少字段: {field}")
                fail(f"  缺少字段: {field}")

        # 检查 description 不是模板占位符
        desc = found.get("description", "")
        if desc and ("Computes the " + self.op_name + " operation" in desc
                     or "Computes the " + self.op_id + " operation" in desc):
            self.warnings.append("operators.yaml description 是模板占位符，应写实际描述")
            warn("  description 是模板占位符 — 应从 PyTorch 文档提取实际描述")

        labels = found.get("labels", [])
        if "KernelGen" not in labels:
            self.warnings.append("operators.yaml labels 中缺少 KernelGen")
            warn("  labels 中缺少 'KernelGen'（新增算子应包含）")
        else:
            ok("  labels 包含 'KernelGen'")

        if "aten" not in labels:
            self.warnings.append("operators.yaml labels 中缺少 aten 标签")
            warn("  labels 中缺少 'aten'")

        # 检查 for 字段是否包含正确的 aten op name（保留原始下划线）
        for_list = found.get("for", [])
        if for_list and self.op_name not in for_list:
            self.warnings.append(
                f"operators.yaml for 字段中未包含 '{self.op_name}'（aten op 原始名称应保留下划线）"
            )
            warn(f"  for 字段建议包含 '{self.op_name}'")

    def check_test_file(self):
        section("测试文件检查")
        if not os.path.isfile(self.test_path):
            # 检查是否用了错误的文件名（带下划线）
            if self.wrong_test_path and os.path.isfile(self.wrong_test_path):
                self.errors.append(
                    f"测试文件名错误: test_{self.op_name}.py → 应为 test_{self.op_id}.py（去掉前导下划线）"
                )
                fail(f"文件名错误: test_{self.op_name}.py → 应为 test_{self.op_id}.py")
            else:
                self.errors.append(f"测试文件不存在: {self.test_path}")
                fail(f"文件不存在: tests/test_{self.op_id}.py")
            return

        ok(f"文件存在: tests/test_{self.op_name}.py")

        with open(self.test_path) as f:
            content = f.read()

        # pytest mark 检查（使用去掉下划线的 op_id）
        correct_mark = f"@pytest.mark.{self.op_id}"
        wrong_mark = f"@pytest.mark.{self.op_name}" if self.has_leading_underscore else None

        if correct_mark in content:
            ok(f"pytest mark 正确: {correct_mark}")
        elif wrong_mark and wrong_mark in content:
            self.errors.append(
                f"测试文件 pytest mark 使用了 '{wrong_mark}'（带下划线），应改为 '{correct_mark}'"
            )
            fail(f"pytest mark 错误: {wrong_mark} → 应为 {correct_mark}")
        else:
            self.errors.append(f"测试文件缺少 {correct_mark}")
            fail(f"缺少 pytest mark: {correct_mark}")

        if "from . import accuracy_utils as utils" in content:
            ok("使用相对导入 accuracy_utils")
        elif "from tests import accuracy_utils" in content:
            self.errors.append("测试文件使用了绝对导入而非相对导入")
            fail("应使用 'from . import accuracy_utils as utils'（相对导入）")
        else:
            self.warnings.append("测试文件中未找到 accuracy_utils 导入")
            warn("未找到 accuracy_utils 导入")

        if "flag_gems.use_gems()" in content:
            ok("使用 flag_gems.use_gems() 上下文")
        else:
            self.warnings.append("测试文件中未使用 flag_gems.use_gems()")
            warn("未找到 flag_gems.use_gems() — 确认测试方式是否正确")

        if "gems_assert_close" in content or "gems_assert_equal" in content:
            ok("使用 gems_assert_close/equal 进行比较")
        else:
            self.errors.append("测试文件未使用 gems_assert_close 或 gems_assert_equal")
            fail("未使用 utils.gems_assert_close 或 utils.gems_assert_equal")

        if "print(" in content:
            self.errors.append("测试文件中使用了 print()")
            fail("包含 print() — 禁止在 test case 中 print")

        if "utils.to_reference" in content:
            ok("使用 utils.to_reference 获取 golden reference")
        else:
            self.warnings.append("测试文件未使用 utils.to_reference")
            warn("未使用 utils.to_reference — 确认 golden reference 来源")

        # 私有 API 检查
        self._check_private_torch_api(content, "测试文件")

        # dtype 硬编码检查
        self._check_dtype_hardcoding(content, "测试文件",
                                     correct_const="utils.FLOAT_DTYPES")

        # gems_assert_close 禁止 rtol 参数
        if re.search(r"gems_assert_close\s*\([^)]*rtol\s*=", content, re.DOTALL):
            self.errors.append("测试文件中 gems_assert_close 不接受 rtol 参数")
            fail("gems_assert_close 使用了 rtol — 仅支持 atol")
        else:
            ok("gems_assert_close 未使用 rtol")

        # 测试函数命名规范
        bad_names = re.findall(r"def\s+(test_(?:perf|accuracy)_\w+)\s*\(", content)
        if bad_names:
            self.warnings.append(f"测试函数命名不规范: {bad_names}，应为 test_<op>")
            warn(f"函数命名: {', '.join(bad_names)} → 应为 test_<op>")
        else:
            ok("测试函数命名规范")

        # 显式 .cpu() / .to(torch.float64) 检测
        for i, line in enumerate(content.split("\n"), 1):
            code_part = line.split("#")[0]
            if "to_reference" in code_part:
                continue
            if ".cpu()" in code_part:
                self.warnings.append(f"测试文件第 {i} 行使用 .cpu() — 建议用 utils.to_reference()")
                warn(f"第 {i} 行: .cpu() → 建议用 utils.to_reference(inp, True)")
                break
            if ".to(torch.float64)" in code_part:
                self.warnings.append(f"测试文件第 {i} 行使用 .to(torch.float64)")
                warn(f"第 {i} 行: .to(torch.float64) → 建议用 utils.to_reference()")
                break

    def check_benchmark_file(self):
        section("Benchmark 文件检查")
        if not os.path.isfile(self.bench_path):
            if self.wrong_bench_path and os.path.isfile(self.wrong_bench_path):
                self.errors.append(
                    f"benchmark 文件名错误: test_{self.op_name}.py → 应为 test_{self.op_id}.py（去掉前导下划线）"
                )
                fail(f"文件名错误: test_{self.op_name}.py → 应为 test_{self.op_id}.py")
            else:
                self.errors.append(f"benchmark 文件不存在: {self.bench_path}")
                fail(f"文件不存在: benchmark/test_{self.op_id}.py")
            return

        ok(f"文件存在: benchmark/test_{self.op_id}.py")

        with open(self.bench_path) as f:
            content = f.read()

        # pytest mark 检查（使用去掉下划线的 op_id）
        correct_mark = f"@pytest.mark.{self.op_id}"
        wrong_mark = f"@pytest.mark.{self.op_name}" if self.has_leading_underscore else None

        if correct_mark in content:
            ok(f"pytest mark 正确: {correct_mark}")
        elif wrong_mark and wrong_mark in content:
            self.errors.append(
                f"benchmark pytest mark 使用了 '{wrong_mark}'（带下划线），应改为 '{correct_mark}'"
            )
            fail(f"pytest mark 错误: {wrong_mark} → 应为 {correct_mark}")
        else:
            self.errors.append(f"benchmark 缺少 {correct_mark}")
            fail(f"缺少 pytest mark: {correct_mark}")

        if "from . import base" in content:
            ok("使用相对导入 base 模块")
        else:
            self.warnings.append("benchmark 未使用相对导入 base")
            warn("未使用 'from . import base' — 应使用 benchmark 封装类")

        benchmark_classes = [
            "UnaryPointwiseBenchmark",
            "BinaryPointwiseBenchmark",
            "UnaryReductionBenchmark",
            "UnaryPointwiseIsCloseBenchmark",
            "GenericBenchmark",
            "BlasBenchmark",
        ]
        found_class = False
        for cls in benchmark_classes:
            if cls in content:
                found_class = True
                ok(f"使用 benchmark 封装类: {cls}")
                break

        if not found_class:
            if "bench.run()" in content or ".run()" in content:
                ok("使用了 benchmark 运行方法")
            else:
                self.warnings.append("benchmark 未使用标准封装类")
                warn("未使用标准 benchmark 封装类 — 确认是否为自定义 benchmark")

        if "print(" in content:
            self.warnings.append("benchmark 中有 print()")
            warn("包含 print() — 建议移除")

        # op_name 检查（应使用去掉下划线的 op_id）
        if self.has_leading_underscore:
            wrong_op_name = f'op_name="{self.op_name}"'
            correct_op_name = f'op_name="{self.op_id}"'
            if wrong_op_name in content:
                self.errors.append(
                    f"benchmark op_name 使用了 '{self.op_name}'（带下划线），应为 '{self.op_id}'"
                )
                fail(f"op_name 错误: {wrong_op_name} → 应为 {correct_op_name}")
            elif correct_op_name in content:
                ok(f"op_name 正确: {correct_op_name}")

        # 私有 API 检查
        self._check_private_torch_api(content, "benchmark 文件")

        # dtype 硬编码检查
        self._check_dtype_hardcoding(content, "benchmark 文件",
                                     correct_const="consts.FLOAT_DTYPES")

        # benchmark 函数命名规范（禁止 test_perf_ / test_accuracy_ 前缀）
        bad_bench_names = re.findall(r"def\s+(test_(?:perf|accuracy)_\w+)\s*\(", content)
        if bad_bench_names:
            self.errors.append(f"benchmark 函数命名不规范: {bad_bench_names}，应为 test_<op>")
            fail(f"函数命名: {', '.join(bad_bench_names)} → 应为 test_<op>（去掉 perf_/accuracy_ 前缀）")
        else:
            ok("benchmark 函数命名规范")

    def _check_private_torch_api(self, content, file_label):
        """检查测试/benchmark 中是否直接调用了 torch._ 私有 API。
        私有 API 在不同 PyTorch 版本中可能不存在，应使用公开 API。
        """
        private_calls = re.findall(r"torch\.(_[a-z]\w*)\(", content)
        # 过滤掉 torch._C 等模块级调用和常见合法用法
        skip = {"_C", "_jit_internal", "_utils", "_dynamo"}
        private_calls = [c for c in private_calls if c not in skip]
        if private_calls:
            unique = sorted(set(private_calls))
            self.errors.append(
                f"{file_label}中直接调用了 torch 私有 API: {', '.join('torch.' + c for c in unique)}"
                f"。私有 API 在不同 PyTorch 版本中可能不存在，应使用对应的公开 API"
            )
            fail(
                f"调用了私有 API: {', '.join('torch.' + c for c in unique)}"
                f" → 应替换为公开 API"
            )
        else:
            ok(f"未调用 torch 私有 API")

    def _check_dtype_hardcoding(self, content, file_label, correct_const):
        """检查 dtype 是否使用了硬编码列表而非统一常量。
        如果硬编码行的上一行有注释说明原因（如 CUDA 不支持某精度），降级为 ok。
        多 dtype 硬编码列表（如 [torch.float32, torch.float16, torch.bfloat16]）无注释报 error。
        """
        # 多 dtype 硬编码模式（parametrize 中常见）
        multi_dtype_patterns = [
            r"\[torch\.float32,\s*torch\.float16,\s*torch\.bfloat16\]",
            r"\[torch\.float16,\s*torch\.float32,\s*torch\.bfloat16\]",
            r"\[torch\.bfloat16,\s*torch\.float16,\s*torch\.float32\]",
            r"\[torch\.float32,\s*torch\.float16\]",
            r"\[torch\.float32,\s*torch\.float64\]",
            r"\[torch\.float16,\s*torch\.float32\]",
        ]
        # 单 dtype 硬编码模式
        single_dtype_patterns = [
            r"\[torch\.float32\]",
            r"\[torch\.float64\]",
            r"\[torch\.float16\]",
            r"\[torch\.bfloat16\]",
        ]
        lines = content.split("\n")

        def _has_comment_above(line_no):
            if line_no > 0:
                prev_line = lines[line_no - 1].strip()
                if prev_line.startswith("#"):
                    return True
            return False

        # 检查多 dtype 硬编码（强制 error）
        for pattern in multi_dtype_patterns:
            match = re.search(pattern, content)
            if match:
                match_pos = match.start()
                line_no = content[:match_pos].count("\n")
                if _has_comment_above(line_no):
                    ok(f"dtype 硬编码 {match.group()}（有注释说明原因，允许）")
                    return
                self.errors.append(
                    f"{file_label}中 dtype 使用了硬编码 {match.group()}，应使用 {correct_const}"
                    f"（如因 CUDA 限制无法使用全部精度，需在上一行加 # 注释说明原因）"
                )
                fail(f"dtype 硬编码: {match.group()} → 应使用 {correct_const}（或加注释说明原因）")
                return

        # 检查单 dtype 硬编码
        for pattern in single_dtype_patterns:
            match = re.search(pattern, content)
            if match:
                match_pos = match.start()
                line_no = content[:match_pos].count("\n")
                if _has_comment_above(line_no):
                    ok(f"dtype 硬编码 {match.group()}（有注释说明原因，允许）")
                    return
                self.errors.append(
                    f"{file_label}中 dtype 使用了硬编码 {match.group()}，应使用 {correct_const}"
                    f"（需在上一行加 # 注释说明原因）"
                )
                fail(f"dtype 硬编码: {match.group()} → 应使用 {correct_const}（或加注释说明原因）")
                return

        if correct_const.split(".")[-1] in content or "FLOAT_DTYPES" in content or "INT_DTYPES" in content:
            ok("dtype 使用统一常量")
        else:
            self.errors.append(f"{file_label}中未检测到标准 dtype 常量，也未找到带注释的硬编码 dtype")
            fail(f"未检测到 {correct_const} 且无带注释的 dtype 硬编码")

    def check_code_quality(self):
        section("代码质量检查")

        for filepath in [self.kernel_path, self.test_path, self.bench_path]:
            if not os.path.isfile(filepath):
                continue
            with open(filepath) as f:
                content = f.read()
            if not content.endswith("\n"):
                relpath = os.path.relpath(filepath, self.repo_dir)
                self.warnings.append(f"{relpath} 文件末尾缺少换行")
                warn(f"{relpath} 文件末尾缺少换行 — end-of-file-fixer 会报错")

        for filepath in [self.kernel_path, self.test_path, self.bench_path]:
            if not os.path.isfile(filepath):
                continue
            with open(filepath) as f:
                lines = f.readlines()
            for i, line in enumerate(lines, 1):
                if line.rstrip() != line.rstrip("\n").rstrip():
                    relpath = os.path.relpath(filepath, self.repo_dir)
                    self.warnings.append(f"{relpath}:{i} 行尾有空白字符")
                    warn(f"{relpath}:{i} 行尾空白 — trailing-whitespace hook 会报错")
                    break

        for filepath in [self.kernel_path, self.test_path, self.bench_path]:
            if not os.path.isfile(filepath):
                continue
            with open(filepath) as f:
                lines = f.readlines()
            for i, line in enumerate(lines, 1):
                if len(line.rstrip("\n")) > 120:
                    relpath = os.path.relpath(filepath, self.repo_dir)
                    self.warnings.append(f"{relpath}:{i} 行长度超过 120 字符")
                    warn(f"{relpath}:{i} 行长度 {len(line.rstrip())} > 120 — flake8 会报错")
                    break

    def check_upstream_conflict(self):
        section("上游冲突检查")
        try:
            result = subprocess.run(
                ["git", "show", f"upstream/master:src/flag_gems/ops/{self.op_name}.py"],
                capture_output=True,
                text=True,
                cwd=self.repo_dir,
            )
            if result.returncode == 0:
                self.errors.append(f"算子 {self.op_name} 已存在于上游 upstream/master")
                fail(f"算子已存在于上游! 不应提交此 PR")
                return
        except FileNotFoundError:
            pass

        ok(f"算子 {self.op_name} 未在上游发现冲突")

    def check_git_commit_message(self):
        section("Git Commit 检查")
        try:
            result = subprocess.run(
                ["git", "log", "upstream/master..HEAD", "--format=%B", "-1"],
                capture_output=True,
                text=True,
                cwd=self.repo_dir,
            )
            if result.returncode != 0 or not result.stdout.strip():
                warn("无新 commit（分支上尚无提交），跳过 commit message 检查")
                return
            msg = result.stdout
            if re.search(r"co-authored-by", msg, re.IGNORECASE):
                self.errors.append("commit message 包含 Co-Authored-By，会导致 CLA CI 失败")
                fail("commit message 包含 Co-Authored-By — 禁止!")
            else:
                ok("commit message 不含 Co-Authored-By")
        except Exception as e:
            warn(f"无法读取 git commit message: {e}")

    def check_inplace_mark(self):
        section("Inplace Mark 检查")
        for filepath, label in [(self.test_path, "测试文件"), (self.bench_path, "benchmark")]:
            if not os.path.isfile(filepath):
                continue
            with open(filepath) as f:
                content = f.read()

            marks = set(re.findall(r"@pytest\.mark\.(\w+)", content))
            # 去掉 pytest 内置 mark
            builtin = {"parametrize", "skip", "skipif", "xfail", "usefixtures", "filterwarnings"}
            marks -= builtin

            if "inplace" in marks:
                self.errors.append(f"{label}包含 @pytest.mark.inplace — 不要加 inplace mark")
                fail(f"{label}: 发现 @pytest.mark.inplace — 应删除")

            # 检查是否有多余的 mark（不属于当前算子）
            expected_marks = {self.op_id}
            # inplace 版本的 mark
            if self.op_name.endswith("_"):
                expected_marks.add(self.op_id)
            extra = marks - expected_marks
            if extra:
                self.warnings.append(f"{label}包含多余的 pytest mark: {extra}")
                warn(f"{label}: 多余 mark {extra} — 确认是否属于本算子")

        ok("inplace mark 检查完成")

    def check_yaml_config_consistency(self):
        """yaml 'for' 列表 vs _FULL_CONFIG 注册名交叉验证。"""
        section("YAML/Config 一致性检查")

        # 提取 yaml for 列表
        yaml_for = set()
        if os.path.isfile(self.yaml_path):
            with open(self.yaml_path) as f:
                try:
                    data = yaml.safe_load(f)
                except yaml.YAMLError:
                    warn("yaml 解析失败，跳过一致性检查")
                    return
            for op in data.get("ops", []):
                if op.get("id") == self.op_id:
                    yaml_for = set(op.get("for", []))
                    break

        if not yaml_for:
            warn("yaml 中未找到 for 列表，跳过一致性检查")
            return

        # 提取 _FULL_CONFIG 中该算子的注册 aten name
        config_aten = set()
        if os.path.isfile(self.top_init_path):
            with open(self.top_init_path) as f:
                init_content = f.read()
            config_match = re.search(
                r"_FULL_CONFIG\s*=\s*\((.+?)\)\s*(?:\n\n|$)", init_content, re.DOTALL
            )
            if config_match:
                config_text = config_match.group(1)
                # 匹配所有 ("aten_name", func_name, ...) 条目
                for m in re.finditer(
                    r'\(\s*["\']([^"\']+)["\']\s*,\s*(\w+)', config_text
                ):
                    aten_name, func_name = m.groups()
                    # 该算子的注册：func_name 匹配 op_name 或 op_id（含 inplace 后缀）
                    base_func = func_name.rstrip("_")
                    if base_func == self.op_name or base_func == self.op_id or func_name == self.op_name:
                        config_aten.add(aten_name)

        if not config_aten:
            warn("_FULL_CONFIG 中未找到该算子注册，跳过一致性检查")
            return

        # 比较
        # yaml for 中的名字用于 aten dispatch，config 中也是 aten name
        {name.split(".")[0] for name in yaml_for}
        {name.split(".")[0] for name in config_aten}

        yaml_only = yaml_for - config_aten
        config_only = config_aten - yaml_for

        if yaml_only:
            self.warnings.append(f"yaml 'for' 包含但 _FULL_CONFIG 未注册: {yaml_only}")
            warn(f"yaml 有但 config 无: {yaml_only}")
        if config_only:
            self.warnings.append(f"_FULL_CONFIG 注册但 yaml 'for' 未包含: {config_only}")
            warn(f"config 有但 yaml 无: {config_only}")
        if not yaml_only and not config_only:
            ok(f"yaml 'for' 与 _FULL_CONFIG 一致: {yaml_for}")

    def check_fallback_recursion(self):
        """检测 kernel 中是否有 torch.<op_name>() 调用导致无限递归 dispatch。"""
        section("Fallback 递归检测")
        if not os.path.isfile(self.kernel_path):
            warn("kernel 文件不存在，跳过")
            return

        with open(self.kernel_path) as f:
            content = f.read()

        # 收集该算子可能的 torch.xxx 调用形式
        op_variants = {self.op_name, self.op_id}
        if self.op_name.endswith("_"):
            op_variants.add(self.op_name.rstrip("_"))

        dangerous_calls = []
        for line_no, line in enumerate(content.split("\n"), 1):
            code_part = line.split("#")[0]
            if "torch.ops.aten." in code_part or "torch.ops." in code_part:
                continue
            for variant in op_variants:
                pattern = rf"torch\.{re.escape(variant)}\s*\("
                if re.search(pattern, code_part):
                    dangerous_calls.append((line_no, variant, line.strip()))

        if dangerous_calls:
            for line_no, variant, line_text in dangerous_calls:
                self.errors.append(
                    f"kernel 第 {line_no} 行调用了 torch.{variant}()，"
                    f"会触发无限递归 dispatch。应使用 torch.ops.aten.{variant}() 或纯 Triton 实现"
                )
                fail(f"第 {line_no} 行: torch.{variant}() → 无限递归! 应改为 torch.ops.aten.{variant}()")
        else:
            ok("未检测到递归 dispatch 风险")

    def check_anti_hack(self):
        """anti_hack.py Layer 1 AST 扫描。"""
        section("Anti-hack 检查")
        if not os.path.isfile(self.kernel_path):
            warn("kernel 文件不存在，跳过")
            return

        anti_hack_path = os.environ.get(
            "ANTI_HACK_SCRIPT", "/workspace/scripts/anti_hack.py"
        )
        if not os.path.isfile(anti_hack_path):
            warn(f"anti_hack.py 不存在: {anti_hack_path}，跳过")
            return

        try:
            spec = importlib.util.spec_from_file_location("anti_hack", anti_hack_path)
            anti_hack = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(anti_hack)

            with open(self.kernel_path) as f:
                code = f.read()

            is_hack, reason = anti_hack.check_code(code, backend="torch")
            if is_hack:
                self.errors.append(f"anti-hack 检测到问题: {reason}")
                fail(f"anti-hack Layer 1 失败:\n    {reason}")
            else:
                ok("anti-hack Layer 1 检查通过")
        except Exception as e:
            warn(f"anti-hack 检查异常: {e}")

    def check_anti_hack_layer2(self):
        """Layer 2: 禁用 triton.jit 后重跑，验证 kernel 确实在做 Triton 计算。"""
        section("Anti-hack Layer 2 (dual execution)")
        if not os.path.isfile(self.kernel_path):
            warn("kernel 文件不存在，跳过")
            return

        anti_hack_path = os.environ.get(
            "ANTI_HACK_SCRIPT", "/workspace/scripts/anti_hack.py"
        )
        if not os.path.isfile(anti_hack_path):
            warn(f"anti_hack.py 不存在: {anti_hack_path}，跳过 Layer 2")
            return

        try:
            import torch
            if not torch.cuda.is_available():
                warn("无 GPU 可用，跳过 Layer 2 dual-execution 检查")
                return

            spec = importlib.util.spec_from_file_location("anti_hack", anti_hack_path)
            anti_hack = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(anti_hack)

            sys.path.insert(0, os.path.join(self.repo_dir, "src"))
            op_module = importlib.import_module(f"flag_gems.ops.{self.op_name}")

            wrapper_func = getattr(op_module, self.op_name, None)
            if wrapper_func is None:
                warn(f"无法导入 wrapper 函数 '{self.op_name}'，跳过 Layer 2")
                return

            # 构造小 tensor 输入用于 dual-execution 检查
            import inspect
            sig = inspect.signature(wrapper_func)
            params = list(sig.parameters.keys())

            # 尝试用小 tensor 调用
            test_input = torch.randn(2, 3, 4, 4, device="cuda", dtype=torch.float32)
            try:
                # 通用调用：大部分 op 第一个参数是 input tensor
                if len(params) >= 2:
                    # 尝试获取第二个参数的默认值
                    second_param = sig.parameters[params[1]]
                    if second_param.default is not inspect.Parameter.empty:
                        kwargs = {params[0]: test_input}
                    else:
                        kwargs = {params[0]: test_input}
                else:
                    kwargs = {params[0]: test_input}

                is_hack, reason = anti_hack.dual_execution_check(
                    lambda **kw: wrapper_func(**kw), kwargs, rtol=1e-3, atol=1e-3
                )

                if is_hack:
                    self.errors.append(
                        f"anti-hack Layer 2 失败: kernel 禁用 triton.jit 后结果不变，"
                        f"说明未使用 Triton 进行实际计算。{reason}"
                    )
                    fail(f"Layer 2 失败: kernel 未使用 Triton 计算!\n    {reason}")
                else:
                    ok("anti-hack Layer 2 通过（kernel 确实依赖 Triton 计算）")
            except Exception as e:
                # 如果调用失败（参数不匹配等），不阻塞
                warn(f"Layer 2 跳过（调用异常: {type(e).__name__}: {e}）")
        except ImportError as e:
            warn(f"Layer 2 跳过（导入失败: {e}）")
        except Exception as e:
            warn(f"Layer 2 检查异常: {e}")
        finally:
            if os.path.join(self.repo_dir, "src") in sys.path:
                sys.path.remove(os.path.join(self.repo_dir, "src"))

    def check_single_op_per_pr(self):
        section("单算子 PR 检查")
        try:
            result = subprocess.run(
                ["git", "diff", "--name-only", "upstream/master..HEAD"],
                capture_output=True,
                text=True,
                cwd=self.repo_dir,
            )
            if result.returncode != 0:
                warn("无法获取 git diff（可能缺少 upstream remote），跳过")
                return

            changed = [f for f in result.stdout.strip().split("\n") if f]
            op_files = [
                f for f in changed
                if f.startswith("src/flag_gems/ops/")
                and f.endswith(".py")
                and not f.endswith("__init__.py")
            ]

            if len(op_files) > 1:
                other_ops = [
                    f for f in op_files
                    if f.rsplit("/", 1)[-1].replace(".py", "") != self.op_name
                ]
                if other_ops:
                    self.errors.append(
                        f"PR 包含多个算子文件: {op_files}。每个 PR 只能提交一个算子"
                    )
                    fail(f"检测到多个算子文件: {', '.join(op_files)}")
                else:
                    ok(f"PR 只修改了 {self.op_name} 相关文件")
            else:
                ok(f"PR 只包含一个算子: {self.op_name}")
        except Exception as e:
            warn(f"单算子检查异常: {e}")

    def check_use_tl_extra_stubs(self):
        section("@use_tl_extra 桩函数检查")
        if not os.path.isfile(self.kernel_path):
            return

        with open(self.kernel_path) as f:
            content = f.read()

        # 匹配 @use_tl_extra 装饰的函数（可能跟 @triton.jit 一起）
        stub_pattern = re.compile(
            r"@use_tl_extra\s+(?:@\w[\w.]*\s+)*def\s+(\w+)\s*\(", re.MULTILINE
        )
        stubs = stub_pattern.findall(content)

        if not stubs:
            ok("无 @use_tl_extra 桩函数")
            return

        unused = []
        for func in stubs:
            # 统计函数名出现次数（排除 def 行本身）
            call_pattern = re.compile(rf"(?<!def\s)\b{re.escape(func)}\s*\(")
            calls = call_pattern.findall(content)
            if len(calls) == 0:
                unused.append(func)

        if unused:
            self.errors.append(f"@use_tl_extra 桩函数未被调用，应删除: {', '.join(unused)}")
            fail(f"未使用的 @use_tl_extra 桩: {', '.join(unused)}")
        else:
            ok(f"@use_tl_extra 桩函数均被使用: {', '.join(stubs)}")

    def check_hardcoded_sizes(self):
        """检查 kernel/test/benchmark 中硬编码的 block size 或 shapes 是否有注释。"""
        section("硬编码超参检查")

        checks = [
            (self.kernel_path, "kernel", r"^\s*(BLOCK(?:_SIZE)?)\s*=\s*(\d+)"),
            (self.kernel_path, "kernel", r"^\s*(_BLOCK)\s*=\s*(\d+)"),
            (self.test_path, "test", r"^\s*(\w*SHAPES)\s*=\s*\["),
            (self.bench_path, "benchmark", r"^\s*(\w*SHAPES)\s*=\s*\["),
            (self.bench_path, "benchmark", r"^\s*(self\.shapes)\s*=\s*\["),
            (self.test_path, "test", r"^\s*(shape)\s*=\s*\([\d,\s]+\)"),
            (self.bench_path, "benchmark", r"^\s*(shape)\s*=\s*\([\d,\s]+\)"),
        ]

        found_any = False
        for filepath, label, pattern in checks:
            if not os.path.isfile(filepath):
                continue
            with open(filepath) as f:
                lines = f.readlines()

            for i, line in enumerate(lines):
                if "triton.Config" in line:
                    continue
                match = re.match(pattern, line)
                if not match:
                    continue

                found_any = True
                var_name = match.group(1)
                has_comment = False
                if i > 0:
                    prev = lines[i - 1].strip()
                    if prev.startswith("#"):
                        has_comment = True

                relpath = os.path.relpath(filepath, self.repo_dir)
                if has_comment:
                    ok(f"{relpath}:{i+1} {var_name} 硬编码（有注释说明）")
                else:
                    self.errors.append(
                        f"{relpath}:{i+1} {var_name} 硬编码但无注释说明原因"
                    )
                    fail(f"{relpath}:{i+1} {var_name} 硬编码无注释 — 需在上方加 # 注释说明原因")

        if not found_any:
            ok("无硬编码超参（或使用 autotune）")

    def check_benchmark_case_count(self):
        section("Benchmark Case 数量")
        if not os.path.isfile(self.bench_path):
            warn("benchmark 文件不存在")
            return

        try:
            result = subprocess.run(
                [
                    "python", "-m", "pytest", self.bench_path,
                    "--collect-only", "-q", "--level", "core",
                ],
                capture_output=True,
                text=True,
                cwd=self.repo_dir,
                timeout=30,
            )
            match = re.search(r"(\d+)\s+tests?\s+collected", result.stdout)
            if not match:
                match = re.search(r"(\d+)\s+item", result.stdout)
            if match:
                count = int(match.group(1))
                ok(f"benchmark case 数量: {count} (--level core)")
                self._bench_case_count = count
            else:
                warn(f"无法解析 case 数量，输出: {result.stdout[:200]}")
        except subprocess.TimeoutExpired:
            warn("pytest --collect-only 超时")
        except Exception as e:
            warn(f"case 数量检查异常: {e}")

    def check_alias_wrappers(self):
        """Rule 16: 检测无意义别名封装（如 _j1 = tl_extra_shim.j1）"""
        section("别名封装检查")
        if not os.path.isfile(self.kernel_path):
            return

        with open(self.kernel_path) as f:
            content = f.read()

        alias_pattern = re.compile(
            r"^(\w+)\s*=\s*(\w+(?:\.\w+)+)\s*$", re.MULTILINE
        )
        aliases = []
        for m in alias_pattern.finditer(content):
            lhs = m.group(1)
            rhs = m.group(2)
            if lhs.startswith("_") or lhs.startswith("logger"):
                continue
            if "shim" in rhs or "libdevice" in rhs or "tl_extra" in rhs:
                aliases.append(f"{lhs} = {rhs}")

        if aliases:
            for a in aliases:
                self.warnings.append(f"kernel 中可能存在无意义别名封装: {a}")
                warn(f"别名封装: {a} — 建议直接内联调用")
        else:
            ok("无无意义别名封装")

    def check_nan_handling(self):
        """Rule 36: nan 比较必须使用 gems_assert_close(equal_nan=True)"""
        section("NaN 处理检查")
        if not os.path.isfile(self.test_path):
            return

        with open(self.test_path) as f:
            content = f.read()

        has_nan_input = bool(re.search(
            r"nan|torch\.nan|float\(['\"]nan['\"]\)|torch\.full.*nan", content, re.IGNORECASE
        ))
        has_equal_nan = "equal_nan=True" in content or "equal_nan = True" in content

        if has_nan_input and not has_equal_nan:
            self.warnings.append("测试涉及 NaN 但未使用 equal_nan=True")
            warn("检测到 NaN 相关输入但未用 gems_assert_close(equal_nan=True)")
        elif has_nan_input and has_equal_nan:
            ok("NaN 测试正确使用 equal_nan=True")
        else:
            ok("无 NaN 相关测试（跳过）")

    def check_worktree_diff(self):
        """Rule 19/32: 对比 PR 代码与 worktree 原始代码，确认一致性"""
        section("Worktree 一致性检查")
        worktree_dir = os.path.join(self.repo_dir, ".worktrees", f"gen-{self.op_name}")
        if not os.path.isdir(worktree_dir):
            worktree_dir = os.path.join(self.repo_dir, ".worktrees", f"gen-{self.op_id}")
        if not os.path.isdir(worktree_dir):
            warn(f"未找到 worktree 目录（gen-{self.op_name}），跳过一致性检查")
            return

        wt_kernel = os.path.join(worktree_dir, "src", "flag_gems", "ops", f"{self.op_name}.py")
        pr_kernel = self.kernel_path

        if os.path.isfile(wt_kernel) and os.path.isfile(pr_kernel):
            with open(wt_kernel) as f:
                wt_content = f.read()
            with open(pr_kernel) as f:
                pr_content = f.read()

            [line.strip() for line in wt_content.strip().splitlines() if line.strip()]
            [line.strip() for line in pr_content.strip().splitlines() if line.strip()]

            wt_comments = [line for line in wt_content.splitlines() if line.strip().startswith("#")]
            pr_comments = [line for line in pr_content.splitlines() if line.strip().startswith("#")]

            if len(pr_comments) < len(wt_comments) - 2:
                self.warnings.append(
                    f"kernel 注释行数减少: worktree={len(wt_comments)}, PR={len(pr_comments)}"
                )
                warn(f"kernel 注释行数减少 ({len(wt_comments)} → {len(pr_comments)}) — 确认未误删注释")
            else:
                ok(f"kernel 注释保留完整 (worktree={len(wt_comments)}, PR={len(pr_comments)})")

            wt_func_count = len(re.findall(r"^\s*def\s+\w+", wt_content, re.MULTILINE))
            pr_func_count = len(re.findall(r"^\s*def\s+\w+", pr_content, re.MULTILINE))
            if pr_func_count > wt_func_count + 2:
                self.warnings.append(f"PR kernel 函数数量({pr_func_count})多于 worktree({wt_func_count})")
                warn(f"PR 中额外函数 — worktree {wt_func_count} vs PR {pr_func_count}")
            elif pr_func_count < wt_func_count - 1:
                self.warnings.append(f"PR kernel 函数数量({pr_func_count})少于 worktree({wt_func_count})")
                warn(f"PR 中删减了函数 — worktree {wt_func_count} vs PR {pr_func_count}")
            else:
                ok(f"kernel 函数数量一致 (worktree={wt_func_count}, PR={pr_func_count})")
        else:
            warn("worktree 中未找到 kernel 文件，跳过对比")

    def check_dtype_assert_in_wrapper(self):
        """Rule 31: 不支持某些 dtype 时 wrapper 中应加 assert"""
        section("Wrapper dtype Assert 检查")
        if not os.path.isfile(self.kernel_path):
            return

        with open(self.kernel_path) as f:
            content = f.read()

        if not os.path.isfile(self.test_path):
            return

        with open(self.test_path) as f:
            test_content = f.read()

        uses_limited_dtype = bool(re.search(
            r"\[torch\.float32\]|\[torch\.float64\]|\[torch\.float32,\s*torch\.float64\]",
            test_content
        ))

        if not uses_limited_dtype:
            ok("测试使用全量 dtype，无需 assert")
            return

        has_dtype_assert = bool(re.search(
            r"assert.*\.dtype|assert.*dtype\s*(==|!=|in|not in)",
            content
        ))
        has_dtype_check = bool(re.search(
            r"if.*\.dtype.*not in|if.*\.dtype\s*!=|raise\s+.*dtype|raise\s+.*type",
            content
        ))

        if has_dtype_assert or has_dtype_check:
            ok("wrapper 中有 dtype 验证")
        else:
            self.warnings.append(
                "测试仅覆盖有限 dtype，但 wrapper 中未发现 dtype assert/check — 建议加 assert 明确拒绝不支持的 dtype"
            )
            warn("测试用有限 dtype 但 wrapper 无 dtype 验证 — 建议加 assert")

    def _check_out_variant_coverage(self, out_func):
        """检查 _out 变体在 test 和 benchmark 中是否有覆盖。"""
        base_name = out_func[:-4]  # remove "_out"
        for filepath, label in [(self.test_path, "测试文件"), (self.bench_path, "benchmark")]:
            if not os.path.isfile(filepath):
                continue
            with open(filepath) as f:
                content = f.read()
            if out_func in content or f"{base_name}_out" in content:
                ok(f"{label}覆盖了 _out 变体: {out_func}")
            else:
                self.errors.append(
                    f"kernel 导出了 {out_func}，但{label}中无对应测试"
                )
                fail(f"{label}未覆盖 _out 变体: {out_func}")

    def _check_duplicate_functions(self, content, filepath):
        try:
            tree = ast.parse(content)
        except SyntaxError:
            return

        func_names = []
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):
                func_names.append(node.name)

        seen = set()
        duplicates = set()
        for name in func_names:
            if name in seen:
                duplicates.add(name)
            seen.add(name)

        if duplicates:
            relpath = os.path.relpath(filepath, self.repo_dir)
            self.errors.append(f"{relpath} 中有重复函数定义: {', '.join(duplicates)}")
            fail(f"重复函数定义: {', '.join(duplicates)}")
        else:
            ok("无重复函数定义")

    def _check_alphabetical_order_init(self, content):
        import_lines = re.findall(r"^from flag_gems\.ops\.(\w+) import", content, re.MULTILINE)
        if import_lines:
            sorted_lines = sorted(import_lines, key=lambda x: (not x.startswith("_"), x))
            if import_lines == sorted_lines:
                ok("import 行按字母序排列")
            else:
                for i, (actual, expected) in enumerate(zip(import_lines, sorted_lines)):
                    if actual != expected:
                        self.warnings.append(f"ops/__init__.py import 顺序可能不对（{actual} vs {expected}）")
                        warn(f"import 顺序可能不对 — isort 可自动修复")
                        break

    def print_summary(self):
        section("检查汇总")
        print(f"\n  算子: {self.op_name}")
        if self.has_leading_underscore:
            print(f"  算子 ID（mark/yaml）: {self.op_id}")
        print(f"  错误: {Colors.FAIL}{len(self.errors)}{Colors.END}")
        print(f"  警告: {Colors.WARN}{len(self.warnings)}{Colors.END}")

        if self.errors:
            print(f"\n  {Colors.FAIL}{Colors.BOLD}必须修复:{Colors.END}")
            for e in self.errors:
                print(f"    - {e}")

        if self.warnings:
            print(f"\n  {Colors.WARN}{Colors.BOLD}建议修复:{Colors.END}")
            for w in self.warnings:
                print(f"    - {w}")

        if not self.errors:
            print(f"\n  {Colors.OK}{Colors.BOLD}所有必要检查通过 ✓{Colors.END}")
        else:
            print(f"\n  {Colors.FAIL}{Colors.BOLD}存在 {len(self.errors)} 个必须修复的问题 ✗{Colors.END}")

    def get_changed_files(self):
        files = [
            f"src/flag_gems/ops/{self.op_name}.py",
            "src/flag_gems/ops/__init__.py",
            "src/flag_gems/__init__.py",
            f"tests/test_{self.op_id}.py",
            f"benchmark/test_{self.op_id}.py",
            "conf/operators.yaml",
        ]
        return [f for f in files if os.path.isfile(os.path.join(self.repo_dir, f))]


def main():
    parser = argparse.ArgumentParser(description="FlagGems 算子 PR 提交前检查")
    parser.add_argument("operator", help="算子名称（如 special_erfcx, _cholesky_solve_helper）")
    parser.add_argument(
        "--repo-dir",
        default=os.environ.get("FLAGGEMS_REPO", "/workspace/FlagGems_minimax_2_7_pr"),
        help="FlagGems 仓库路径",
    )
    parser.add_argument("--list-files", action="store_true", help="仅输出涉及的文件列表")
    parser.add_argument("--strict", action="store_true", help="严格模式: warning 也视为失败")
    args = parser.parse_args()

    checker = OperatorChecker(args.operator, args.repo_dir)

    if args.list_files:
        for f in checker.get_changed_files():
            print(f)
        return

    print(f"{Colors.BOLD}FlagGems 算子 PR 检查: {args.operator}{Colors.END}")
    print(f"仓库路径: {args.repo_dir}")

    success = checker.run_all()
    if args.strict and checker.warnings:
        print(f"\n  {Colors.FAIL}{Colors.BOLD}--strict 模式: {len(checker.warnings)} 个 warning 视为失败 ✗{Colors.END}")
        sys.exit(1)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
