#!/usr/bin/env python3
"""从 worktree 自动提取算子代码并准备 6 个 PR 文件。

用法:
    python extract_from_worktree.py <op> --repo-dir /path/to/FlagGems
    python extract_from_worktree.py <op> --dry-run  # 只预览不写入

自动完成:
    1. 复制 kernel 文件（确保 KernelGen 首行）
    2. 从 worktree 提取测试函数 → tests/test_<op>.py
    3. 从 worktree 提取 benchmark → benchmark/test_<op>.py
    4. 按字母序插入 ops/__init__.py（import + __all__）
    5. 按字母序插入 __init__.py（_FULL_CONFIG）
    6. 按字母序插入 conf/operators.yaml
"""

import argparse
import os
import re
import shutil
import sys
import textwrap

import yaml

DEFAULT_REPO = "/workspace/FlagGems_minimax_2_7_pr"
KERNELGEN_HEADER = "# Generated by KernelGen: https://github.com/flagos-ai/KernelGen\n"

# accuracy_utils symbols that need `utils.` prefix when converting imports
UTILS_SYMBOLS = [
    "FLOAT_DTYPES", "ALL_FLOAT_DTYPES", "INT_DTYPES", "ALL_INT_DTYPES",
    "BOOL_TYPES", "COMPLEX_DTYPES", "POINTWISE_SHAPES", "SPECIAL_SHAPES",
    "DISTRIBUTION_SHAPES", "REDUCTION_SHAPES", "to_reference",
    "gems_assert_close", "gems_assert_equal",
]


class Colors:
    OK = "\033[92m"
    FAIL = "\033[91m"
    BOLD = "\033[1m"
    CYAN = "\033[96m"
    END = "\033[0m"


def ok(msg):
    print(f"  {Colors.OK}✓{Colors.END} {msg}")


def warn(msg):
    print(f"  {Colors.CYAN}⚠{Colors.END} {msg}")


def fatal(msg):
    print(f"  {Colors.FAIL}✗ FATAL: {msg}{Colors.END}")
    sys.exit(1)


def section(msg):
    print(f"\n{Colors.BOLD}[{msg}]{Colors.END}")


def get_op_id(op_name):
    return op_name.lstrip("_")


# ---------------------------------------------------------------------------
# Step 1: Kernel file
# ---------------------------------------------------------------------------


def extract_kernel(op, worktree, repo, dry_run):
    section("Step 1: Kernel 文件")
    src = os.path.join(worktree, f"src/flag_gems/ops/{op}.py")
    dst = os.path.join(repo, f"src/flag_gems/ops/{op}.py")

    if not os.path.isfile(src):
        fatal(f"worktree kernel 不存在: {src}")

    with open(src) as f:
        content = f.read()

    if not content.startswith("# Generated by KernelGen"):
        content = KERNELGEN_HEADER + content

    if dry_run:
        ok(f"[DRY] 将写入 {dst} ({len(content.splitlines())} 行)")
    else:
        with open(dst, "w") as f:
            f.write(content)
        ok(f"已复制: {dst}")


# ---------------------------------------------------------------------------
# Step 2: Test file
# ---------------------------------------------------------------------------


def find_test_function(op, worktree):
    """Find and extract test function(s) for the operator from worktree.

    Search priority:
    1. test_accuracy_<op_id> — most common pattern
    2. test_accuracy_<op_name> — underscore-prefixed variant
    3. test_<op_id> — no accuracy prefix (reflection_pad3d, embedding etc.)
    4. Any function decorated with @pytest.mark.<op_id>
    """
    tests_dir = os.path.join(worktree, "tests")
    op_id = get_op_id(op)

    candidates = [
        f"test_accuracy_{op_id}",
        f"test_accuracy_{op}" if op.startswith("_") else None,
        f"test_{op_id}",
    ]
    candidates = [c for c in candidates if c]

    for target_func in candidates:
        for fname in os.listdir(tests_dir):
            if not fname.endswith(".py"):
                continue
            fpath = os.path.join(tests_dir, fname)
            with open(fpath) as f:
                content = f.read()
            if f"def {target_func}" in content:
                return fpath, content, target_func

    # Fallback: find by @pytest.mark.<op_id>
    mark_pattern = f"@pytest.mark.{op_id}"
    for fname in os.listdir(tests_dir):
        if not fname.endswith(".py"):
            continue
        fpath = os.path.join(tests_dir, fname)
        with open(fpath) as f:
            content = f.read()
        if mark_pattern in content:
            # Find the first test function after the mark
            match = re.search(rf"{re.escape(mark_pattern)}.*?def\s+(test_\w+)", content, re.DOTALL)
            if match:
                return fpath, content, match.group(1)

    return None, None, None


def find_all_related_test_functions(content, op_id, primary_func_name):
    """Find all test functions related to the operator in the same file.

    Looks for functions decorated with @pytest.mark.<op_id>.
    """
    func_names = []
    mark = f"@pytest.mark.{op_id}"

    # Use regex to find all def lines preceded (somewhere above) by the mark
    # Pattern: @pytest.mark.<op_id> followed eventually by def test_xxx
    for m in re.finditer(
        rf"^{re.escape(mark)}\s*\n(?:.*\n)*?^\s*def\s+(test_\w+)",
        content, re.MULTILINE
    ):
        fn = m.group(1)
        if fn not in func_names:
            func_names.append(fn)

    if not func_names and primary_func_name:
        func_names = [primary_func_name]

    return func_names


def extract_function_block(content, func_name):
    """Extract a function and its decorators from source code."""
    lines = content.split("\n")
    func_start = None
    decorator_start = None
    func_end = None

    for i, line in enumerate(lines):
        if f"def {func_name}" in line:
            func_start = i
            # Walk backwards to find decorators
            decorator_start = i
            j = i - 1
            while j >= 0:
                stripped = lines[j].strip()
                if stripped.startswith("@") or stripped == "":
                    if stripped.startswith("@"):
                        decorator_start = j
                    j -= 1
                else:
                    break
            break

    if func_start is None:
        return None

    # Find function end (next def/class at same or lower indent, or EOF)
    indent = len(lines[func_start]) - len(lines[func_start].lstrip())
    for i in range(func_start + 1, len(lines)):
        line = lines[i]
        if line.strip() == "":
            continue
        line_indent = len(line) - len(line.lstrip())
        if line_indent <= indent and (line.strip().startswith("def ") or
                                       line.strip().startswith("class ") or
                                       line.strip().startswith("@")):
            # Check if decorator belongs to this function
            if i > func_start + 1:
                func_end = i
                break
    if func_end is None:
        func_end = len(lines)

    # Trim trailing blank lines
    while func_end > decorator_start and lines[func_end - 1].strip() == "":
        func_end -= 1

    return "\n".join(lines[decorator_start:func_end])


def convert_test_imports(func_block, op):
    """Convert direct accuracy_utils imports to `utils.` prefix style."""
    op_id = get_op_id(op)
    result = func_block

    # Replace function name: test_accuracy_<op> → test_<op>
    result = re.sub(rf"def test_accuracy_{re.escape(op_id)}\b",
                    f"def test_{op_id}", result)
    if op.startswith("_"):
        result = re.sub(rf"def test_accuracy_{re.escape(op)}\b",
                        f"def test_{op_id}", result)

    # Replace bare symbols with utils. prefix
    for sym in UTILS_SYMBOLS:
        # Only replace bare occurrences (not already prefixed)
        result = re.sub(rf"(?<!\.)(?<!\w){re.escape(sym)}\b", f"utils.{sym}", result)

    # Replace device reference
    result = result.replace("device=device", "device=flag_gems.device")

    # Remove vendor-specific branches
    result = re.sub(
        r"\s*if flag_gems\.vendor_name\s*==\s*[\"']kunlunxin[\"'].*?(?=\n\S|\n@|\Z)",
        "", result, flags=re.DOTALL
    )

    return result


def extract_test(op, worktree, repo, dry_run):
    section("Step 2: Test 文件")
    op_id = get_op_id(op)
    dst = os.path.join(repo, f"tests/test_{op_id}.py")

    fpath, content, func_name = find_test_function(op, worktree)
    if not fpath:
        fatal(f"worktree 中未找到 test_accuracy_{op_id} 或 test_{op_id} 函数")

    ok(f"找到测试: {os.path.basename(fpath)}:{func_name}")

    # Find all related test functions (including variants like _list_padding, _empty_padding)
    all_funcs = find_all_related_test_functions(content, op_id, func_name)
    ok(f"找到 {len(all_funcs)} 个相关测试函数: {', '.join(all_funcs)}")

    blocks = []
    for fn in all_funcs:
        block = extract_function_block(content, fn)
        if block:
            block = convert_test_imports(block, op)
            blocks.append(block)

    if not blocks:
        fatal(f"无法提取函数 {func_name}")

    combined_blocks = "\n\n\n".join(blocks)

    test_content = (
        "import pytest\n"
        "import torch\n"
        "\n"
        "import flag_gems\n"
        "\n"
        "from . import accuracy_utils as utils\n"
        "\n"
        "\n"
        f"{combined_blocks}\n"
    )

    if dry_run:
        ok(f"[DRY] 将写入 {dst}")
        print(f"    预览:\n{test_content[:500]}")
    else:
        with open(dst, "w") as f:
            f.write(test_content)
        ok(f"已生成: {dst}")


# ---------------------------------------------------------------------------
# Step 3: Benchmark file
# ---------------------------------------------------------------------------


def find_benchmark_code(op, worktree):
    """Find benchmark code for the operator in worktree."""
    op_id = get_op_id(op)
    bench_dir = os.path.join(worktree, "benchmark")

    for fname in os.listdir(bench_dir):
        if not fname.endswith(".py"):
            continue
        fpath = os.path.join(bench_dir, fname)
        with open(fpath) as f:
            content = f.read()
        if (f"mark.{op_id}" in content or f'op_name="{op_id}"' in content
                or f'"{op_id}"' in content):
            return fpath, content

    return None, None


def extract_benchmark_block(content, op, source_file):
    """Extract benchmark related code (class, input_fn, test function)."""
    op_id = get_op_id(op)
    lines = content.split("\n")
    blocks = []

    # Strategy 1: Find standalone class + test function (e.g., RandintBenchmark)
    class_pattern = re.compile(rf"class \w*{re.escape(op_id)}\w*Benchmark", re.IGNORECASE)
    for i, line in enumerate(lines):
        if class_pattern.search(line):
            cls_name = line.split("class ")[1].split("(")[0].split(":")[0]
            block = extract_function_block(content, cls_name)
            if block:
                blocks.append(("class", block))

    # Strategy 2: Find input_fn for this op
    input_fn_names = [
        f"{op_id}_input_fn", f"_{op_id}_input_fn", f"_input_fn",
    ]
    for fn_name in input_fn_names:
        for i, line in enumerate(lines):
            if f"def {fn_name}" in line:
                block = extract_function_block(content, fn_name)
                if block:
                    blocks.append(("input_fn", block))
                break

    # Strategy 3: Find standalone test function (e.g., test_perf_randint)
    test_patterns = [
        rf"def test_(?:perf_)?{re.escape(op_id)}\b",
        rf"def test_{re.escape(op_id)}\b",
    ]
    for pat in test_patterns:
        for i, line in enumerate(lines):
            if re.search(pat, line):
                fname = re.search(r"def (\w+)", line).group(1)
                block = extract_function_block(content, fname)
                if block:
                    blocks.append(("test", block))
                break
        if any(t == "test" for t, _ in blocks):
            break

    # Strategy 4: op in a parametrized list → generate standalone benchmark
    if not any(t == "test" for t, _ in blocks):
        list_entry = _find_list_entry(lines, op_id, source_file)
        if list_entry:
            blocks.append(("list_entry", list_entry))

    return blocks


def _find_list_entry(lines, op_id, source_file):
    """Find op in a parametrized operations list and return benchmark info dict."""
    basename = os.path.basename(source_file) if source_file else ""

    for i, line in enumerate(lines):
        stripped = line.strip()
        if f'"{op_id}"' not in stripped:
            continue
        if "torch." not in stripped:
            continue

        # Parse: ("op_name", torch.op, [dtypes]) or ("op_name", torch.op, input_fn)
        match = re.search(
            rf'\(\s*"{re.escape(op_id)}"\s*,\s*([\w.]+)\s*(?:,\s*(.+?))?\s*\)',
            stripped
        )
        if not match:
            continue

        torch_op = match.group(1)
        third_arg = match.group(2).strip().rstrip(",") if match.group(2) else None

        # Determine benchmark type from file name
        bench_type = "generic"
        if "unary_pointwise" in basename:
            bench_type = "unary"
        elif "binary_pointwise" in basename:
            bench_type = "binary"

        # Determine dtypes
        dtypes = None
        if third_arg:
            if third_arg.startswith("["):
                dtypes = third_arg
            # else it's an input_fn name, leave dtypes as None

        return {
            "type": bench_type,
            "torch_op": torch_op,
            "dtypes": dtypes,
            "op_id": op_id,
        }

    return None


def generate_benchmark_file(blocks, op, bench_source_file):
    """Generate independent benchmark file from extracted blocks."""
    op_id = get_op_id(op)

    has_class = any(t == "class" for t, _ in blocks)
    has_test = any(t == "test" for t, _ in blocks)
    list_entry = next((b for t, b in blocks if t == "list_entry"), None)

    # Case A: standalone class + input_fn + test function → combine them
    if has_class or has_test:
        all_block_text = "\n".join(b for _, b in blocks if isinstance(b, str))
        needs_consts = ("consts." in all_block_text or "FLOAT_DTYPES" in all_block_text
                        or "INT_DTYPES" in all_block_text)

        header = "import pytest\nimport torch\n\nfrom . import base"
        if needs_consts:
            header += ", consts"
        header += "\n"

        parts = [header]
        for btype, block in blocks:
            if not isinstance(block, str):
                continue
            if btype == "test":
                block = re.sub(rf"def test_perf_{re.escape(op_id)}\b",
                               f"def test_{op_id}", block)
            parts.append(f"\n\n{block}")

        content = "\n".join(parts)

        # Add base. prefix to benchmark classes if not already prefixed
        for cls in ["GenericBenchmark", "GenericBenchmarkExcluse1D",
                     "GenericBenchmarkExcluse3D", "GenericBenchmark2DOnly",
                     "GenericBenchmark4DOnly", "UnaryPointwiseBenchmark",
                     "BinaryPointwiseBenchmark", "UnaryReductionBenchmark",
                     "BlasBenchmark", "Benchmark"]:
            content = re.sub(rf"(?<!base\.)(?<!\w){cls}\(", f"base.{cls}(", content)
            content = re.sub(rf"(?<!base\.)(?<!\w){cls}\)", f"base.{cls})", content)
        content = content.replace("base.base.", "base.")

        # Add consts. prefix
        for const in ["FLOAT_DTYPES", "INT_DTYPES", "EXTRA_INT_DTYPES"]:
            content = re.sub(rf"(?<!consts\.)(?<!\w){const}\b", f"consts.{const}", content)
        content = content.replace("consts.consts.", "consts.")

    # Case B: list entry → generate standard benchmark
    elif list_entry:
        info = list_entry
        torch_op = info["torch_op"]
        dtypes_str = info.get("dtypes")

        if info["type"] == "unary":
            cls = "base.UnaryPointwiseBenchmark"
        elif info["type"] == "binary":
            cls = "base.BinaryPointwiseBenchmark"
        else:
            cls = "base.GenericBenchmark"

        # Build dtypes argument
        if dtypes_str:
            dtypes_arg = f"dtypes={dtypes_str}"
            needs_consts = False
        else:
            dtypes_arg = "dtypes=consts.FLOAT_DTYPES"
            needs_consts = True

        header = "import pytest\nimport torch\n\nfrom . import base"
        if needs_consts:
            header += ", consts"
        header += "\n"

        content = f"""{header}


@pytest.mark.{op_id}
def test_{op_id}():
    bench = {cls}(
        op_name="{op_id}",
        torch_op={torch_op},
        {dtypes_arg},
    )
    bench.run()
"""
    else:
        return None

    if not content.endswith("\n"):
        content += "\n"
    return content


def extract_benchmark(op, worktree, repo, dry_run):
    section("Step 3: Benchmark 文件")
    op_id = get_op_id(op)
    dst = os.path.join(repo, f"benchmark/test_{op_id}.py")

    fpath, content = find_benchmark_code(op, worktree)
    if not fpath:
        fatal(f"worktree benchmark 中未找到 {op_id} 相关代码")

    ok(f"找到 benchmark: {os.path.basename(fpath)}")

    blocks = extract_benchmark_block(content, op, fpath)
    if not blocks:
        fatal(f"无法提取 benchmark 代码块")

    ok(f"提取到 {len(blocks)} 个代码块: {[t for t, _ in blocks]}")

    bench_content = generate_benchmark_file(blocks, op, fpath)

    if not bench_content:
        fatal("无法生成 benchmark 文件内容")

    if dry_run:
        ok(f"[DRY] 将写入 {dst}")
        print(f"    预览:\n{bench_content[:500]}")
    else:
        with open(dst, "w") as f:
            f.write(bench_content)
        ok(f"已生成: {dst}")


# ---------------------------------------------------------------------------
# Step 4: ops/__init__.py
# ---------------------------------------------------------------------------


def insert_ops_init(op, worktree, repo, dry_run):
    section("Step 4: ops/__init__.py")
    wt_init = os.path.join(worktree, "src/flag_gems/ops/__init__.py")
    repo_init = os.path.join(repo, "src/flag_gems/ops/__init__.py")

    # Extract import line and __all__ entries from worktree
    with open(wt_init) as f:
        wt_content = f.read()

    import_pattern = rf"^from flag_gems\.ops\.{re.escape(op)} import .+$"
    import_line = None
    for line in wt_content.split("\n"):
        if re.match(import_pattern, line):
            import_line = line
            break

    if not import_line:
        fatal(f"worktree ops/__init__.py 中未找到 {op} 的 import")

    # Extract __all__ names for this op
    all_names = re.findall(rf'from flag_gems\.ops\.{re.escape(op)} import (.+)', import_line)[0]
    names = [n.strip() for n in all_names.split(",")]
    ok(f"import: {import_line}")
    ok(f"导出名: {names}")

    # Read repo file
    with open(repo_init) as f:
        repo_content = f.read()

    # Insert import line in alphabetical order
    repo_lines = repo_content.split("\n")
    import_section_end = 0
    existing_imports = []
    for i, line in enumerate(repo_lines):
        if line.startswith("from flag_gems.ops."):
            existing_imports.append((i, line))
            import_section_end = i

    # Check if already exists
    if any(import_line in line for _, line in existing_imports):
        ok("import 已存在，跳过")
    else:
        # Find insertion point by alphabetical order
        module_name = op
        insert_idx = import_section_end + 1
        for i, line in existing_imports:
            match = re.match(r"from flag_gems\.ops\.(\w+) import", line)
            if match:
                existing_mod = match.group(1)
                sort_key_existing = (not existing_mod.startswith("_"), existing_mod)
                sort_key_new = (not module_name.startswith("_"), module_name)
                if sort_key_new < sort_key_existing:
                    insert_idx = i
                    break
                insert_idx = i + 1

        repo_lines.insert(insert_idx, import_line)
        ok(f"import 插入位置: 行 {insert_idx + 1}")

    # Insert into __all__
    # Find __all__ block
    all_start = None
    all_end = None
    for i, line in enumerate(repo_lines):
        if "__all__" in line and "=" in line:
            all_start = i
        if all_start and line.strip() == "]":
            all_end = i
            break

    if all_start and all_end:
        # Extract current __all__ entries
        all_entries = []
        for i in range(all_start, all_end + 1):
            matches = re.findall(r'"(\w+)"', repo_lines[i])
            all_entries.extend(matches)

        for name in names:
            if name in all_entries:
                ok(f'__all__ 已包含 "{name}"')
                continue

            # Find insertion point
            insert_idx = all_end
            for i in range(all_start + 1, all_end):
                match = re.search(r'"(\w+)"', repo_lines[i])
                if match:
                    existing = match.group(1)
                    if name < existing:
                        insert_idx = i
                        break
                    insert_idx = i + 1

            entry = f'    "{name}",'
            repo_lines.insert(insert_idx, entry)
            all_end += 1
            ok(f'__all__ 插入 "{name}" 在行 {insert_idx + 1}')

    new_content = "\n".join(repo_lines)

    if dry_run:
        ok("[DRY] ops/__init__.py 将被更新")
    else:
        with open(repo_init, "w") as f:
            f.write(new_content)
        ok("ops/__init__.py 已更新")


# ---------------------------------------------------------------------------
# Step 5: _FULL_CONFIG
# ---------------------------------------------------------------------------


def insert_full_config(op, worktree, repo, dry_run):
    section("Step 5: _FULL_CONFIG")
    wt_init = os.path.join(worktree, "src/flag_gems/__init__.py")
    repo_init = os.path.join(repo, "src/flag_gems/__init__.py")

    # Extract config entries from worktree
    with open(wt_init) as f:
        wt_content = f.read()

    # Find all config entries for this op
    op_id = get_op_id(op)
    config_entries = []
    for line in wt_content.split("\n"):
        line_stripped = line.strip()
        if line_stripped.startswith("(") and ("," in line_stripped):
            match = re.match(r'\(\s*"([^"]+)"\s*,\s*(\w+)', line_stripped)
            if match:
                aten_name, func_name = match.groups()
                base_name = aten_name.split(".")[0].lstrip("_")
                if func_name in (op, op_id) or base_name in (op, op_id):
                    config_entries.append(line_stripped.rstrip(",") + ",")

    if not config_entries:
        fatal(f"worktree _FULL_CONFIG 中未找到 {op} 的条目")

    for entry in config_entries:
        ok(f"配置: {entry}")

    # Read repo file
    with open(repo_init) as f:
        repo_content = f.read()

    repo_lines = repo_content.split("\n")

    # Find _FULL_CONFIG block
    config_start = None
    config_end = None
    for i, line in enumerate(repo_lines):
        if "_FULL_CONFIG" in line and "=" in line:
            config_start = i
        if config_start and line.strip() == ")":
            config_end = i
            break

    if not config_start or not config_end:
        fatal("未找到 _FULL_CONFIG 定义")

    # Insert each entry
    for entry in config_entries:
        match = re.match(r'\(\s*"([^"]+)"', entry)
        if not match:
            continue
        aten_name = match.group(1)

        # Check if already exists
        if f'"{aten_name}"' in repo_content:
            ok(f'_FULL_CONFIG 已包含 "{aten_name}"')
            continue

        # Find insertion point by alphabetical order of aten name
        insert_idx = config_end
        for i in range(config_start + 1, config_end):
            line_match = re.search(r'\(\s*"([^"]+)"', repo_lines[i])
            if line_match:
                existing_name = line_match.group(1)
                if aten_name < existing_name:
                    insert_idx = i
                    break
                insert_idx = i + 1

        indent = "    "
        repo_lines.insert(insert_idx, f"{indent}{entry}")
        config_end += 1
        ok(f'_FULL_CONFIG 插入 "{aten_name}" 在行 {insert_idx + 1}')

    new_content = "\n".join(repo_lines)

    if dry_run:
        ok("[DRY] __init__.py 将被更新")
    else:
        with open(repo_init, "w") as f:
            f.write(new_content)
        ok("__init__.py 已更新")


# ---------------------------------------------------------------------------
# Step 6: operators.yaml
# ---------------------------------------------------------------------------


def insert_operators_yaml(op, worktree, repo, dry_run):
    section("Step 6: operators.yaml")
    op_id = get_op_id(op)
    repo_yaml = os.path.join(repo, "conf/operators.yaml")
    wt_yaml = os.path.join(worktree, "conf/operators.yaml")

    with open(repo_yaml) as f:
        repo_data = yaml.safe_load(f)

    # Check if already exists
    existing_ids = [o.get("id") for o in repo_data.get("ops", [])]
    if op_id in existing_ids:
        ok(f"operators.yaml 已包含 id: {op_id}")
        # Still check inplace split below
    else:
        # Try to get entry from worktree yaml
        entry = None
        with open(wt_yaml) as f:
            wt_data = yaml.safe_load(f)
        for wt_op in wt_data.get("ops", []):
            wt_name = wt_op.get("name", wt_op.get("id", ""))
            if wt_name in (op, op_id):
                entry = dict(wt_op)
                if "name" in entry:
                    entry["id"] = op_id
                    del entry["name"]
                break

        if not entry:
            entry = {
                "id": op_id,
                "description": f"Triton kernel implementation for {op}.\n",
                "for": [op],
                "labels": ["aten", "KernelGen"],
                "kind": ["Math"],
                "stages": [{"alpha": "5.1"}],
            }
            warn(f"worktree yaml 无此算子，使用默认条目（description 需人工补充）")
        else:
            labels = entry.get("labels", [])
            if "KernelGen" not in labels:
                labels.append("KernelGen")
                entry["labels"] = labels
            entry["id"] = op_id
            stages = entry.get("stages", {})
            if isinstance(stages, dict):
                entry["stages"] = [{k: v} for k, v in stages.items()]
            ok(f"从 worktree yaml 提取条目")

        # Split: if entry's 'for' list contains both op and op_ (inplace), split them
        for_list = entry.get("for", [])
        inplace_items = [f for f in for_list if f.rstrip(".").endswith("_") and f.rstrip("_.") == op.rstrip("_")]
        non_inplace_items = [f for f in for_list if f not in inplace_items]

        if inplace_items and non_inplace_items:
            warn(f"检测到 for 列表同时包含 inplace 和非 inplace: {for_list}，自动拆分")
            entry["for"] = non_inplace_items
            _insert_yaml_entry(entry, repo_yaml, op_id, existing_ids, dry_run)
            # Create separate inplace entry
            inplace_entry = dict(entry)
            inplace_id = op_id + "_"
            inplace_entry["id"] = inplace_id
            inplace_entry["description"] = f"The in-place version of `{op_id}()`."
            inplace_entry["for"] = inplace_items
            if inplace_id not in existing_ids:
                _insert_yaml_entry(inplace_entry, repo_yaml, inplace_id, existing_ids, dry_run)
                ok(f"已拆分 inplace 变体为独立条目: id={inplace_id}")
        else:
            _insert_yaml_entry(entry, repo_yaml, op_id, existing_ids, dry_run)

    # Check _FULL_CONFIG for inplace variant not in yaml
    wt_init = os.path.join(worktree, "src/flag_gems/__init__.py")
    if os.path.isfile(wt_init):
        with open(wt_init) as f:
            wt_content = f.read()
        inplace_op = op + "_" if not op.endswith("_") else None
        if inplace_op:
            inplace_id = get_op_id(inplace_op)
            inplace_pattern = rf'\(\s*"[^"]*{re.escape(inplace_op)}[^"]*"\s*,'
            if re.search(inplace_pattern, wt_content):
                # Reload to check current state
                with open(repo_yaml) as f:
                    current_data = yaml.safe_load(f)
                current_ids = [o.get("id") for o in current_data.get("ops", [])]
                if inplace_id not in current_ids:
                    inplace_entry = {
                        "id": inplace_id,
                        "description": f"The in-place version of `{op_id}()`.",
                        "for": [inplace_op],
                        "labels": ["aten", "KernelGen"],
                        "kind": ["Math"],
                        "stages": [{"alpha": "5.1"}],
                    }
                    _insert_yaml_entry(inplace_entry, repo_yaml, inplace_id, current_ids, dry_run)
                    ok(f"_FULL_CONFIG 注册了 inplace 变体，已生成独立 yaml 条目: {inplace_id}")


def _insert_yaml_entry(entry, repo_yaml, entry_id, existing_ids, dry_run):
    """Insert a single yaml entry in alphabetical order."""
    if entry_id in existing_ids:
        ok(f"yaml 已包含 id: {entry_id}，跳过")
        return

    with open(repo_yaml) as f:
        yaml_lines = f.readlines()

    insert_line = len(yaml_lines)
    i = 0
    while i < len(yaml_lines):
        match = re.match(r"\s*-\s*id:\s*(\S+)", yaml_lines[i])
        if match:
            existing_id = match.group(1)
            if entry_id < existing_id:
                insert_line = i
                break
        i += 1

    new_lines = []
    new_lines.append(f"  - id: {entry['id']}\n")
    desc = entry.get("description", "").strip()
    if "\n" in desc or len(desc) > 60:
        new_lines.append("    description: |\n")
        for dline in desc.split("\n"):
            new_lines.append(f"      {dline.strip()}\n")
    else:
        new_lines.append(f"    description: {desc}\n")
    new_lines.append("    for:\n")
    for item in entry.get("for", []):
        new_lines.append(f"      - {item}\n")
    new_lines.append("    labels:\n")
    for label in entry.get("labels", ["aten", "KernelGen"]):
        new_lines.append(f"      - {label}\n")
    new_lines.append("    kind:\n")
    for kind in entry.get("kind", ["Math"]):
        new_lines.append(f"      - {kind}\n")
    new_lines.append("    stages:\n")
    stages = entry.get("stages", [{"alpha": "5.1"}])
    if isinstance(stages, list):
        for s in stages:
            if isinstance(s, dict):
                for k, v in s.items():
                    new_lines.append(f"      - {k}: '{v}'\n")
    elif isinstance(stages, dict):
        for k, v in stages.items():
            new_lines.append(f"      - {k}: '{v}'\n")

    yaml_lines[insert_line:insert_line] = new_lines
    ok(f"yaml 插入 id: {entry_id} 在行 {insert_line + 1}")

    if dry_run:
        ok(f"[DRY] operators.yaml 将被更新 ({entry_id})")
    else:
        with open(repo_yaml, "w") as f:
            f.writelines(yaml_lines)
        ok(f"operators.yaml 已更新 ({entry_id})")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(description="从 worktree 自动提取算子代码")
    parser.add_argument("operator", help="算子名称")
    parser.add_argument(
        "--repo-dir",
        default=os.environ.get("FLAGGEMS_REPO", DEFAULT_REPO),
    )
    parser.add_argument("--dry-run", action="store_true", help="只预览不写入")
    args = parser.parse_args()

    op = args.operator
    op_id = get_op_id(op)
    repo = os.path.abspath(args.repo_dir)
    worktree = os.path.join(repo, f".worktrees/gen-{op}")

    print(f"{Colors.BOLD}从 worktree 提取: {op}{Colors.END}")
    print(f"worktree: {worktree}")
    print(f"repo: {repo}")

    if not os.path.isdir(worktree):
        fatal(f"worktree 不存在: {worktree}")

    extract_kernel(op, worktree, repo, args.dry_run)
    extract_test(op, worktree, repo, args.dry_run)
    extract_benchmark(op, worktree, repo, args.dry_run)
    insert_ops_init(op, worktree, repo, args.dry_run)
    insert_full_config(op, worktree, repo, args.dry_run)
    insert_operators_yaml(op, worktree, repo, args.dry_run)

    print(f"\n{Colors.OK}{Colors.BOLD}✓ 6 个文件已准备完毕{Colors.END}")
    print(f"  src/flag_gems/ops/{op}.py")
    print(f"  src/flag_gems/ops/__init__.py")
    print(f"  src/flag_gems/__init__.py")
    print(f"  tests/test_{op_id}.py")
    print(f"  benchmark/test_{op_id}.py")
    print(f"  conf/operators.yaml")
    print(f"\n  接下来运行: CUDA_VISIBLE_DEVICES=<N> python scripts/submit_operator.py {op}")


if __name__ == "__main__":
    main()
